# @generated by @newel/generator-godot — do not edit
class_name AethermiteData
extends Resource

enum Form {
	DUST,
	SHARD,
}

enum State {
	RAW,
	REFINED,
	ENCHANTED,
	CONSUMED,
}

@export var id: String
@export var state: int
@export var form: int
@export var density: float
@export var hardness: float
@export var conductivity: float
@export var magicAffinity: float
