# @generated by @newel/generator-godot — do not edit
# IR version: 3.0.0
extends Resource
class_name AethermiteData

enum Form {
	DUST,
	SHARD,
}

enum State {
	RAW,
	REFINED,
	ENCHANTED,
	CONSUMED,
}
