# @generated by @newel/generator-godot — do not edit
class_name GrassData
extends Resource


@export var id: String
@export var density: float
@export var hardness: float
@export var depthBand: Dictionary
@export var leyGated: bool
