# @generated by @newel/generator-godot — do not edit
class_name VeilsteelData
extends Resource

enum State {
	UNALLOYED,
	REFINED,
	ENCHANTED,
}

@export var id: String
@export var state: int
@export var density: float
@export var hardness: float
@export var conductivity: float
@export var magicAffinity: float
