# @generated by @newel/generator-godot — do not edit
class_name VoiditeData
extends Resource

enum State {
	RAW,
	REFINED,
	ENCHANTED,
}

@export var id: String
@export var state: int
@export var density: float
@export var hardness: float
@export var conductivity: float
@export var magicAffinity: float
