# @generated by @newel/generator-godot — do not edit
class_name LootTableData
extends Resource

enum State {
	SEALED,
	AVAILABLE,
	CLAIMED,
	EXPIRED,
}

@export var id: String
@export var state: int
@export var creatureId: String
@export var despawnSeconds: int
