# @generated by @newel/generator-godot — do not edit
extends Resource
class_name AethermiteBowData

enum Rarity {
	COMMON,
	UNCOMMON,
	RARE,
	EPIC,
	LEGENDARY,
}

enum State {
	PRISTINE,
	WORN,
	DAMAGED,
	BROKEN,
}
