# @generated by @newel/generator-godot — do not edit
class_name AethermiteDustData
extends Resource

enum Rarity {
	COMMON,
	UNCOMMON,
	RARE,
	EPIC,
	LEGENDARY,
}

enum Condition {
	PRISTINE,
	WORN,
	DAMAGED,
	BROKEN,
}
