# @generated by @newel/generator-godot — do not edit
class_name ThornwoodPlankData
extends Resource

enum Rarity {
	COMMON,
	UNCOMMON,
	RARE,
	EPIC,
	LEGENDARY,
}

enum Condition {
	PRISTINE,
	WORN,
	DAMAGED,
	BROKEN,
}

@export var id: String
@export var condition: int
@export var weight: float
@export var rarity: int
@export var stackable: bool
@export var durability: int
