# @generated by @newel/generator-godot — do not edit
# IR version: 3.0.0
extends Resource
class_name ThornwoodPlankData

enum Rarity {
	COMMON,
	UNCOMMON,
	RARE,
	EPIC,
	LEGENDARY,
}

enum State {
	PRISTINE,
	WORN,
	DAMAGED,
	BROKEN,
}
