# @generated by @newel/generator-godot — do not edit
class_name TechAlchemyData
extends Resource

enum Status {
	LOCKED,
	RESEARCHING,
	UNLOCKED,
}

@export var id: String
@export var status: int
@export var researchCost: int
@export var tier: int
@export var tech: Dictionary
