extends Node
## Character slice — data-driven character appearance system (characters.md).
##
## Realizes the design doc as a working vertical slice:
##   - non-humanoid skeletons (humanoid / quadruped / bird / serpent)
##   - bones vs sockets, equipment slots vs sockets, attachment states
##   - body proportions with artistic bounds, mesh hiding, deformation modes
##   - a single 256-entry palette with color indices instead of raw RGB
##   - persistence-as-recipe + multiplayer visual state + derived wear
##   - LOD via per-attachment minLodLevel
##
## Definitions come from GameData (the generated autoload) — skeletons, the
## palette, and appearance recipes live in the fabric
## (fabric/gameplay/characters/*) and are generated by `newel generate`, while
## equipment-visual fields live on the equippable items in GameData.ITEMS. This
## slice only assembles visuals and normalizes recipes; it never hardcodes
## content. The fabric is the single source of truth.
##
## Visuals are modular low-poly placeholders (BoxMesh parts) assembled in code —
## real skinned meshes/textures/clips are asset-production work outside this
## slice's scope, but the decision layer they plug into (locomotion state
## machine, blend curve, facing, approximate foot IK) is implemented per
## characters.md §37.
##
## Plug contract (GameBus signals consumed / emitted):
##   OUT : character_spawned(instance_id, skeleton_id, position)
##         character_appearance_changed(instance_id, appearance)
##
## Public API:
##   create_character(appearance_id, pos)                  -> String (instance_id or "")
##   create_character_from_recipe(recipe, pos)             -> String
##   apply_appearance(instance_id, recipe)                 -> bool
##   get_appearance(instance_id)                           -> Dictionary
##   get_visual_state(instance_id)                         -> Dictionary
##   serialize_appearance(recipe)                          -> Dictionary
##   deserialize_appearance(data)                          -> Dictionary
##   palette_color(index)                                  -> Color
##   get_palette_size()                                    -> int
##   set_lod(level) / get_lod()                            -> void / int
##   is_part_visible(instance_id, part_key)                -> bool

const Locomotion  := preload("res://src/character/locomotion.gd")
const SkeletonRig := preload("res://src/character/skeleton_rig.gd")
const GameDataReader := preload("res://src/core/game_data_reader.gd")
const CharacterMaterial := preload("res://src/character/character_material.gd")

const MIN_LOD := 0
const MAX_LOD := 3

## Palette is a fixed 256 entries (§19): one byte per color index.
const PALETTE_SIZE := 256
const PALETTE_KEY := "DefaultPalette"
const DEFAULT_SKELETON := "HumanoidSkeleton"

## Body-proportion bounds (characters.md §8). Artistic, not engine defaults —
## each combination must survive validation against animations, clothing and
## clipping before finalizing. Kept here as mechanics config (clamping bounds);
## the fabric carries the enumerable content (skeletons, palettes, appearances,
## equipment).
const BODY_PROP_BOUNDS: Dictionary = {
	"height":        { "min": 0.85, "default": 1.00, "max": 1.15 },
	"bodyMass":      { "min": 0.80, "default": 1.00, "max": 1.20 },
	"shoulderWidth": { "min": 0.90, "default": 1.00, "max": 1.10 },
	"armLength":     { "min": 0.90, "default": 1.00, "max": 1.10 },
	"legLength":     { "min": 0.90, "default": 1.00, "max": 1.10 },
	"headScale":     { "min": 0.90, "default": 1.00, "max": 1.10 },
}

## Instance record: { "appearance", "position", "root", "parts" }.
var _instances: Dictionary = {}
## Static so ids stay globally unique across every CharacterSlice instance —
## tests create and free many slices within a single synchronous run(), and a
## per-instance counter reissued "character_0" from each one.
static var _next_id: int = 0
var _lod: int = 0
var _palette: Array = []

## Body-part texture, lazily resolved through AssetOverlay so a mounted
## production pack overrides the committed placeholder without this slice
## ever referencing a private path (§ asset separation).
var _body_texture: ImageTexture = null

## Instance id of the player's own character avatar (set by game_root) — the
## target for combat- and death-driven animation triggers.
var _player_character_id: String = ""

func _ready() -> void:
	_load_palette()
	GameBus.character_attack_requested.connect(_on_attack_requested)
	GameBus.character_death_requested.connect(_on_death_requested)

# ---------------------------------------------------------------------------
# Public — creation
# ---------------------------------------------------------------------------

## Spawn a character from a named appearance recipe in GameData.APPEARANCES.
## Returns the instance_id, or "" if the appearance_id is unknown.
func create_character(appearance_id: String, pos: Vector3) -> String:
	var res: Resource = GameData.APPEARANCES.get(appearance_id, null)
	if res == null:
		push_warning("CharacterSlice: unknown appearance_id '%s'" % appearance_id)
		return ""
	return create_character_from_recipe(_appearance_to_recipe(res), pos)

## Spawn a character from a raw appearance recipe (persisted / network source).
## The recipe is normalized (unknown fields dropped, proportions clamped) before
## the visual is assembled.
func create_character_from_recipe(recipe: Dictionary, pos: Vector3) -> String:
	var normalized := deserialize_appearance(recipe)
	var iid := "character_%d" % _next_id
	_next_id += 1

	var built: Dictionary = _make_visual(iid, normalized)
	var root: Node3D = built["root"]
	root.position = pos
	add_child(root)

	_instances[iid] = {
		"appearance": normalized,
		"position":   pos,
		"root":       root,
		"rig":        built["rig"],
		"locomotion": built["locomotion"],
		"equipment":  built["equipment"],
		"parts":      built["parts"],
	}
	_apply_lod(iid)

	var skeleton_id: String = str(normalized.get("skeleton", "?"))
	GameBus.character_spawned.emit(iid, skeleton_id, pos)
	print("CharacterSlice: spawned %s [%s] at %s" % [skeleton_id, iid, pos])
	return iid

## Replace an existing instance's appearance recipe (rebuilds the visual).
func apply_appearance(instance_id: String, recipe: Dictionary) -> bool:
	if not _instances.has(instance_id):
		return false
	var normalized := deserialize_appearance(recipe)
	var inst: Dictionary = _instances[instance_id]

	var old_root: Node3D = inst["root"]
	old_root.queue_free()

	var built: Dictionary = _make_visual(instance_id, normalized)
	var root: Node3D = built["root"]
	root.position = inst["position"]
	add_child(root)

	inst["appearance"] = normalized
	inst["root"] = root
	inst["rig"] = built["rig"]
	inst["locomotion"] = built["locomotion"]
	inst["equipment"] = built["equipment"]
	inst["parts"] = built["parts"]
	_apply_lod(instance_id)

	GameBus.character_appearance_changed.emit(instance_id, normalized)
	return true

# ---------------------------------------------------------------------------
# Public — queries
# ---------------------------------------------------------------------------

## Return the normalized appearance recipe for an instance (deep copy).
func get_appearance(instance_id: String) -> Dictionary:
	if not _instances.has(instance_id):
		return {}
	return _instances[instance_id]["appearance"].duplicate(true)

## Assemble the multiplayer visual state (characters.md §32). Derived visual
## state (wear from durability, §23/§33) is computed here and NOT persisted.
func get_visual_state(instance_id: String) -> Dictionary:
	var appearance := get_appearance(instance_id)
	if appearance.is_empty():
		return {}

	var equipment: Dictionary = {}
	var eq_dict: Dictionary = appearance.get("equipment", {})
	for slot in eq_dict:
		var entry: Dictionary = eq_dict[slot]
		equipment[slot] = entry.duplicate(true)
		equipment[slot]["wear"] = _wear_level(float(entry.get("durability", 1.0)))

	return {
		"identity": { "skeleton": appearance.get("skeleton", ""), "body": appearance.get("body", "") },
		"body":     { "proportions": appearance.get("proportions", {}), "skinColor": appearance.get("skinColor", 0) },
		"face":     { "head": appearance.get("head", ""), "eyes": appearance.get("eyes", ""), "eyeColor": appearance.get("eyeColor", 0), "beard": appearance.get("beard", "") },
		"hair":     { "asset": appearance.get("hair", ""), "color": appearance.get("hairColor", 0) },
		"equipment": equipment,
	}

## Whether a named part (e.g. "hair", "Chest") is currently visible under the
## active LOD. Exposed for debug/HUD and tests.
func is_part_visible(instance_id: String, part_key: String) -> bool:
	if not _instances.has(instance_id):
		return false
	var parts: Dictionary = _instances[instance_id]["parts"]
	if not parts.has(part_key):
		return false
	return parts[part_key]["node"].visible

## Live node for a named part (body_chest/body_legs/head/hair/beard or an
## equipment slot), or null when the part is absent. Exposed for tests and the
## debug HUD.
func get_part_node(instance_id: String, part_key: String) -> Node3D:
	if not _instances.has(instance_id):
		return null
	var parts: Dictionary = _instances[instance_id]["parts"]
	if not parts.has(part_key):
		return null
	return parts[part_key].get("node", null)

## The ShaderMaterial on a named part (body_chest / body_legs / head / hair /
## beard / an equipment slot), or null when the part is absent. Every part now
## shares ONE material (§20), so this returns that shared material — use
## get_part_shader_parameter() to read a part's per-instance palette/channel
## values (they live on the mesh, not the shared material).
func get_part_material(instance_id: String, part_key: String) -> ShaderMaterial:
	var node := get_part_node(instance_id, part_key)
	if node == null:
		return null
	var mat = node.material_override
	return mat if mat is ShaderMaterial else null

## Read a per-instance shader parameter from a part's mesh (set via
## set_instance_shader_parameter). Returns null when the part is absent or the
## parameter was never set. Exposed for Phase 22 palette-swap and channel tests
## to read/write per-instance values directly.
func get_part_shader_parameter(instance_id: String, part_key: String, param: String):
	var node := get_part_node(instance_id, part_key)
	if node == null or not (node is GeometryInstance3D):
		return null
	return (node as GeometryInstance3D).get_instance_shader_parameter(param)

## The shared 256×1 palette texture (characters.md §19), built once from the
## fabric palette. Every part samples this same texture; a palette swap writes a
## shader index, never a new texture. Exposed for tests and tooling.
func get_palette_texture() -> ImageTexture:
	return CharacterMaterial.palette_texture(_palette_colors())

## Swap one palette index channel on a part's mesh without creating a new
## texture or material (§20). `channel` is base_index / primary_index /
## secondary_index / accent_index. Returns false when the part is absent or the
## channel key is unknown (see CharacterMaterial.set_index).
func apply_palette_index(instance_id: String, part_key: String, channel: String, index: int) -> bool:
	var node := get_part_node(instance_id, part_key)
	if node == null or not (node is GeometryInstance3D):
		return false
	return CharacterMaterial.set_index(node as GeometryInstance3D, channel, index) >= 0

# ---------------------------------------------------------------------------
# Public — recipe (de)serialization (characters.md §30, §31)
# ---------------------------------------------------------------------------

## A recipe is already JSON-safe (String / int / float / Dictionary / Array).
## Return a deep copy so callers cannot mutate live instance state.
func serialize_appearance(recipe: Dictionary) -> Dictionary:
	return recipe.duplicate(true)

## Normalize a recipe: validate skeleton against GameData.SKELETONS, clamp
## proportions to artistic bounds, clamp color indices to [0, PALETTE_SIZE), and
## drop equipment whose item is not an equippable entry in GameData.ITEMS.
func deserialize_appearance(data: Dictionary) -> Dictionary:
	var recipe: Dictionary = {}

	var skeleton: String = str(data.get("skeleton", DEFAULT_SKELETON))
	if not GameData.SKELETONS.has(skeleton):
		skeleton = DEFAULT_SKELETON
	recipe["skeleton"] = skeleton

	recipe["body"] = str(data.get("body", "human_body_01"))
	recipe["proportions"] = _normalize_proportions(data.get("proportions", {}))

	recipe["skinColor"] = _color_index(data.get("skinColor", 12))
	recipe["head"] = str(data.get("head", "head_01"))
	recipe["eyes"] = str(data.get("eyes", "eyes_01"))
	recipe["eyeColor"] = _color_index(data.get("eyeColor", 225))
	recipe["hair"] = str(data.get("hair", "hair_short_01"))
	recipe["hairColor"] = _color_index(data.get("hairColor", 40))
	recipe["beard"] = str(data.get("beard", "none"))
	recipe["beardColor"] = _color_index(data.get("beardColor", 40))

	var eq_raw = data.get("equipment", {})
	var eq_out: Dictionary = {}
	if eq_raw is Dictionary:
		var eq_in: Dictionary = eq_raw
		for slot in eq_in:
			var entry = eq_in[slot]
			if entry is Dictionary:
				var item_id: String = str(entry.get("item", ""))
				var def := _equipment_def(item_id)
				# Reject an entry whose dict key doesn't match the item's own
				# equipmentSlot — otherwise a recipe could claim any equippable
				# item into any slot key regardless of what it actually fits.
				if not def.is_empty() and str(def.get("slot", "")) == str(slot):
					eq_out[slot] = _normalize_equipment(entry)
	recipe["equipment"] = eq_out

	return recipe

# ---------------------------------------------------------------------------
# Public — palette (characters.md §19)
# ---------------------------------------------------------------------------

## Return the color at a palette index (clamped to [0, PALETTE_SIZE)).
func palette_color(index: int) -> Color:
	if _palette.is_empty():
		_load_palette()
	if _palette.is_empty():
		return Color.WHITE
	return _palette[clampi(index, 0, _palette.size() - 1)]

func get_palette_size() -> int:
	if _palette.is_empty():
		_load_palette()
	return _palette.size()

# ---------------------------------------------------------------------------
# Public — LOD (characters.md §35, §36)
# ---------------------------------------------------------------------------

func set_lod(level: int) -> void:
	_lod = clampi(level, MIN_LOD, MAX_LOD)
	for iid in _instances:
		_apply_lod(iid)

func get_lod() -> int:
	return _lod

# ---------------------------------------------------------------------------
# Public — equipment + animation (ROADMAP Phase 20)
# ---------------------------------------------------------------------------

## Equip an item onto a character slot (replaces any existing equipment there).
## `item_key` is a GameData.ITEMS key; `state` is the attachment state
## (equipped/sheathed/stored/hidden). Returns true on success.
func apply_equipment(instance_id: String, slot: String, item_key: String, state: String = "equipped") -> bool:
	if not _instances.has(instance_id):
		return false
	var def := _equipment_def(item_key)
	# Reject an item that doesn't actually fit this slot — mirrors
	# deserialize_appearance()'s recipe-side guard so a caller can't force any
	# equippable item into any slot regardless of what it fits (§30).
	if def.is_empty() or str(def.get("slot", "")) != slot:
		return false

	var inst: Dictionary = _instances[instance_id]
	var rig = inst["rig"]
	var props: Dictionary = inst["appearance"].get("proportions", {})

	var entry := _normalize_equipment({
		"item": item_key,
		"state": state,
	})
	var rec: Dictionary = _attach_equipment(rig, slot, entry, props)
	if rec.is_empty():
		return false

	# Replace any existing mesh on the slot.
	var equipment: Dictionary = inst["equipment"]
	if equipment.has(slot):
		var old: Dictionary = equipment[slot]
		var old_node: Node3D = old.get("node", null)
		if old_node != null:
			old_node.queue_free()

	equipment[slot] = rec
	inst["parts"][slot] = { "node": rec["node"], "min_lod": int(rec["def"].get("minLodLevel", 0)) }

	# Reflect the change in the appearance recipe so persistence / visual state
	# stay consistent with the live instance.
	var app: Dictionary = inst["appearance"]
	var eq: Dictionary = app.get("equipment", {})
	eq[slot] = entry
	app["equipment"] = eq
	_apply_lod(instance_id)
	GameBus.character_appearance_changed.emit(instance_id, app)
	return true

## Unequip a slot (free the mesh and drop it from the appearance recipe).
func clear_equipment(instance_id: String, slot: String) -> bool:
	if not _instances.has(instance_id):
		return false
	var inst: Dictionary = _instances[instance_id]
	var equipment: Dictionary = inst["equipment"]
	if not equipment.has(slot):
		return false
	var rec: Dictionary = equipment[slot]
	var node: Node3D = rec.get("node", null)
	if node != null:
		node.queue_free()
	equipment.erase(slot)
	if inst["parts"].has(slot):
		inst["parts"].erase(slot)
	var app: Dictionary = inst["appearance"]
	if app.has("equipment"):
		var eq: Dictionary = app["equipment"]
		if eq.has(slot):
			eq.erase(slot)
	# Un-equipping can lift a hideRegions hide another slot no longer shares
	# (or the cleared slot could have been the last thing hiding a part).
	_apply_lod(instance_id)
	GameBus.character_appearance_changed.emit(instance_id, app)
	return true

## Advance the locomotion state machine for an instance. Returns the resulting
## Locomotion.State int, and emits character_state_changed on any transition.
func update_locomotion(instance_id: String, speed: float, grounded: bool, velocity_y: float, delta: float) -> int:
	if not _instances.has(instance_id):
		return -1
	var loco = _instances[instance_id]["locomotion"]
	var before: int = loco.get_state()
	var after: int = loco.update(speed, grounded, velocity_y, delta)
	if after != before:
		GameBus.character_state_changed.emit(instance_id, loco.state_name())
	return after

func get_locomotion_state(instance_id: String) -> int:
	if not _instances.has(instance_id):
		return -1
	return _instances[instance_id]["locomotion"].get_state()

func get_locomotion_state_name(instance_id: String) -> String:
	if not _instances.has(instance_id):
		return ""
	return _instances[instance_id]["locomotion"].state_name()

## Play the attack animation on an instance (transient ATTACK state).
func trigger_attack(instance_id: String) -> void:
	if not _instances.has(instance_id):
		return
	_instances[instance_id]["locomotion"].trigger_attack()

## Play the death animation on an instance (terminal DEATH state).
func trigger_death(instance_id: String) -> void:
	if not _instances.has(instance_id):
		return
	_instances[instance_id]["locomotion"].trigger_death()

## Foot IK targets for an instance. `terrain_height` is a Callable(Vector2)→float.
func get_foot_ik_targets(instance_id: String, terrain_height: Callable) -> Dictionary:
	if not _instances.has(instance_id):
		return {}
	var inst: Dictionary = _instances[instance_id]
	var props: Dictionary = inst["appearance"].get("proportions", {})
	var rig = inst["rig"]
	var landmarks: Dictionary = SkeletonRig.compute_landmarks(rig.get_body_shape_coefficients(), props)
	return SkeletonRig.compute_foot_targets(
		terrain_height,
		inst["position"],
		landmarks["hip_y"],
		landmarks["leg_reach"],
		landmarks["foot_side"],
		0.0
	)

## Drive a live-controlled instance (the player avatar) from its controller's
## per-frame state: position/facing sync, locomotion state, and an approximate
## foot-IK vertical offset (characters.md §37 — hip-height adjustment only, no
## per-leg bone solver). `horizontal_velocity` and `speed` are the controller's
## XZ velocity and its length; `terrain_height` is a Callable(Vector2)->float.
## Foot targets are stashed as root metadata ("foot_ik_l"/"foot_ik_r") for
## later consumers (e.g. a future real IK solver) instead of being discarded.
func sync_player_avatar(
	instance_id: String,
	position: Vector3,
	horizontal_velocity: Vector3,
	velocity_y: float,
	grounded: bool,
	delta: float,
	terrain_height: Callable
) -> void:
	if not _instances.has(instance_id):
		return
	var inst: Dictionary = _instances[instance_id]
	var root: Node3D = inst["root"]
	var rig = inst["rig"]
	var props: Dictionary = inst["appearance"].get("proportions", {})
	var landmarks: Dictionary = SkeletonRig.compute_landmarks(rig.get_body_shape_coefficients(), props)

	# Turning — rotate toward the horizontal movement direction at the rig's
	# turnSpeed (radians/sec), rather than snapping to face it instantly.
	var speed: float = Vector2(horizontal_velocity.x, horizontal_velocity.z).length()
	if speed > 0.05:
		var target_yaw := atan2(horizontal_velocity.x, horizontal_velocity.z)
		root.rotation.y = rotate_toward(root.rotation.y, target_yaw, rig.get_turn_speed() * delta)

	# Approximate foot IK — sample terrain under both feet at the controller's
	# XZ position and pull the whole body up/down by the higher foot's height
	# offset from its rest hip height, instead of leaving the avatar floating
	# over slopes/stairs or sinking into them (no per-leg bone solver — §37).
	var feet: Dictionary = SkeletonRig.compute_foot_targets(
		terrain_height,
		position,
		landmarks["hip_y"],
		landmarks["leg_reach"],
		landmarks["foot_side"],
		0.0
	)
	var ground_y: float = maxf(feet["foot_l"].y, feet["foot_r"].y) - landmarks["hip_y"]
	root.position = Vector3(position.x, ground_y, position.z)
	root.set_meta("foot_ik_l", feet["foot_l"])
	root.set_meta("foot_ik_r", feet["foot_r"])

	inst["position"] = root.position
	update_locomotion(instance_id, speed, grounded, velocity_y, delta)

## Bone names of the instance's skeleton (ordered, parents first).
func get_skeleton_bone_names(instance_id: String) -> Array:
	if not _instances.has(instance_id):
		return []
	return _instances[instance_id]["rig"].get_bone_names()

## Deformation mode recorded for an equipped slot ("" if not equipped).
func get_equipment_deformation_mode(instance_id: String, slot: String) -> String:
	if not _instances.has(instance_id):
		return ""
	var equipment: Dictionary = _instances[instance_id]["equipment"]
	if not equipment.has(slot):
		return ""
	return str(equipment[slot].get("mode", ""))

## Which bone an equipped slot attaches to ("" for RIGID / unattached).
func get_equipment_attached_bone(instance_id: String, slot: String) -> String:
	if not _instances.has(instance_id):
		return ""
	var equipment: Dictionary = _instances[instance_id]["equipment"]
	if not equipment.has(slot):
		return ""
	return str(equipment[slot].get("bone", ""))

## Designate the player's own character avatar (drives combat/death animation).
func set_player_character(instance_id: String) -> void:
	_player_character_id = instance_id

func get_player_character() -> String:
	return _player_character_id

func _on_attack_requested(instance_id: String) -> void:
	trigger_attack(instance_id)

func _on_death_requested(instance_id: String) -> void:
	trigger_death(instance_id)

## Build the equipment-visual definition for an item from GameData.ITEMS.
## Returns {} when the item is missing or has no equipment slot (not equippable).
## `compatibleTags` exists in the fabric but is not yet consumed by the
## placeholder visual; `hideRegions` is consumed by `_apply_lod` (§16).
func _equipment_def(item_id: String) -> Dictionary:
	var res: Resource = GameData.ITEMS.get(item_id, null)
	if res == null:
		return {}
	var slot := GameDataReader.str_field(res, "equipmentSlot", "")
	if slot == "":
		return {}
	return {
		"slot":           slot,
		"deformationMode": GameDataReader.str_field(res, "deformationMode", "RIGID"),
		"masks":           GameDataReader.json_field(res, "masks", {}),
		"attachments":     GameDataReader.json_field(res, "attachments", {}),
		"minLodLevel":     GameDataReader.int_field(res, "minLodLevel", 0),
		"size":            GameDataReader.json_field(res, "size", [0.3, 0.3, 0.3]),
		"metal":           GameDataReader.str_field(res, "metalTone", "none"),
		"emissionColor":   GameDataReader.int_field(res, "emissionColor", 200),
		"hideRegions":     GameDataReader.json_field(res, "hideRegions", []),
	}

## Build a raw appearance recipe Dictionary from a GameData.APPEARANCES resource.
func _appearance_to_recipe(res: Resource) -> Dictionary:
	return {
		"skeleton":    GameDataReader.str_field(res, "skeleton", DEFAULT_SKELETON),
		"body":        GameDataReader.str_field(res, "body", "human_body_01"),
		"proportions": GameDataReader.json_field(res, "proportions", {}),
		"skinColor":   GameDataReader.int_field(res, "skinColor", 12),
		"head":        GameDataReader.str_field(res, "head", "head_01"),
		"eyes":        GameDataReader.str_field(res, "eyes", "eyes_01"),
		"eyeColor":    GameDataReader.int_field(res, "eyeColor", 225),
		"hair":        GameDataReader.str_field(res, "hair", "hair_short_01"),
		"hairColor":   GameDataReader.int_field(res, "hairColor", 40),
		"beard":       GameDataReader.str_field(res, "beard", "none"),
		"beardColor":  GameDataReader.int_field(res, "beardColor", 40),
		"equipment":   GameDataReader.json_field(res, "equipment", {}),
	}

# ---------------------------------------------------------------------------
# Palette construction
# ---------------------------------------------------------------------------

func _load_palette() -> void:
	var res: Resource = GameData.PALETTES.get(PALETTE_KEY, null)
	var entries = GameDataReader.json_field(res, "entries", []) if res != null else []
	_palette = []
	if entries is Array and entries.size() > 0:
		for hex_str in entries:
			_palette.append(Color(str(hex_str)))
	else:
		_palette = _fallback_palette()

## Neutral grayscale fallback so placeholder colors still resolve if the
## generated palette resource is unavailable.
func _fallback_palette() -> Array:
	var out: Array = []
	for i in range(PALETTE_SIZE):
		var g := float(i) / float(PALETTE_SIZE - 1)
		out.append(Color(g, g, g))
	return out

## Named 32-entry region bounds (characters.md §19), read from the generated
## palette's `regions` field (palettes.js) so the metals/emission region numbers
## are never hardcoded in this slice. Falls back to the palettes.js layout when
## the field is absent (defensive against a stale/unregenerated GameData).
func _palette_regions() -> Array:
	var res: Resource = GameData.PALETTES.get(PALETTE_KEY, null)
	var regions = GameDataReader.json_field(res, "regions", []) if res != null else []
	if regions is Array and regions.size() > 0:
		return regions
	return _default_regions()

## Region bounds { "start": int, "end": int } for a named region (e.g. "metals",
## "emission"). Empty {0,0} when the name is unknown.
func _region_bounds(name: String) -> Dictionary:
	for r in _palette_regions():
		if r is Dictionary and str(r.get("name", "")) == name:
			return { "start": int(r.get("start", 0)), "end": int(r.get("end", 0)) }
	return { "start": 0, "end": 0 }

## Mirrors the palettes.js REGIONS layout (8 × 32-entry regions) as a fallback.
func _default_regions() -> Array:
	var names := ["skin", "hair", "primary", "secondary", "accent", "metals", "emission", "eyes"]
	var out: Array = []
	for i in range(names.size()):
		out.append({ "name": names[i], "start": i * 32, "end": (i + 1) * 32 - 1 })
	return out

# ---------------------------------------------------------------------------
# Recipe normalization helpers
# ---------------------------------------------------------------------------

func _normalize_proportions(props) -> Dictionary:
	var src: Dictionary = props if props is Dictionary else {}
	var out: Dictionary = {}
	for key in BODY_PROP_BOUNDS:
		var bounds: Dictionary = BODY_PROP_BOUNDS[key]
		var lo: float = bounds["min"]
		var hi: float = bounds["max"]
		var def: float = bounds["default"]
		var v = src.get(key, def)
		if v is float or v is int:
			out[key] = clampf(float(v), lo, hi)
		else:
			out[key] = def
	return out

func _color_index(v) -> int:
	if v is float or v is int:
		return clampi(int(v), 0, PALETTE_SIZE - 1)
	return 0

func _normalize_equipment(entry: Dictionary) -> Dictionary:
	return {
		"item":           str(entry.get("item", "")),
		"state":          str(entry.get("state", "equipped")),
		"primaryColor":   _color_index(entry.get("primaryColor", 0)),
		"secondaryColor": _color_index(entry.get("secondaryColor", 0)),
		"accentColor":    _color_index(entry.get("accentColor", 0)),
		"durability":     clampf(float(entry.get("durability", 1.0)), 0.0, 1.0),
	}

## Wear tiers (§23): durability → discrete tier, shared by the visual-state
## name (_wear_level) and the shader scalar (_wear_value) so the two never drift.
const WEAR_TIERS: Array = [
	{ "min": 0.9, "name": "New", "value": 0.0 },
	{ "min": 0.6, "name": "Used", "value": 0.35 },
	{ "min": 0.3, "name": "Worn", "value": 0.7 },
	{ "min": 0.0, "name": "Heavily Damaged", "value": 1.0 },
]

func _wear_tier(durability: float) -> Dictionary:
	for tier in WEAR_TIERS:
		if durability >= float(tier["min"]):
			return tier
	return WEAR_TIERS[WEAR_TIERS.size() - 1]

## Wear is derived from durability, never persisted (§23).
func _wear_level(durability: float) -> String:
	return _wear_tier(durability)["name"]

## Discrete shader wear scalar, derived from the same tiers as _wear_level (§23),
## so the shader's wear visually matches the reported wear tier.
func _wear_value(durability: float) -> float:
	return _wear_tier(durability)["value"]

# ---------------------------------------------------------------------------
# LOD
# ---------------------------------------------------------------------------

## A part renders while `_lod <= part.min_lod` and its part key is not hidden by
## a currently-equipped item's `hideRegions` (§16, e.g. a helmet hiding "Hair").
## The hidden set is recomputed from every equipped slot's def each call rather
## than tracked incrementally, so two overlapping hides (and un-equipping one of
## them) always resolve correctly from current state alone.
func _apply_lod(instance_id: String) -> void:
	if not _instances.has(instance_id):
		return
	var inst: Dictionary = _instances[instance_id]
	var parts: Dictionary = inst["parts"]
	var equipment: Dictionary = inst["equipment"]

	var hidden: Dictionary = {}
	var rig = inst.get("rig", null)
	var is_humanoid: bool = rig != null and rig.get_family() == "humanoid"
	for slot in equipment:
		var def: Dictionary = equipment[slot].get("def", {})
		for region in def.get("hideRegions", []):
			var part_key := _region_to_part(str(region), is_humanoid)
			if part_key != "":
				hidden[part_key] = true

	for key in parts:
		var part: Dictionary = parts[key]
		var node: Node3D = part["node"]
		var min_lod: int = part.get("min_lod", 0)
		node.visible = _lod <= min_lod and not hidden.get(key, false)

## Map a fabric mesh-hiding region (characters.md §16) onto the placeholder
## part key it corresponds to in `parts`. The humanoid placeholder body is
## split into a chest region (torso/shoulders/arms) and a legs region, so
## BodyChest/BodyShoulders/BodyArms collapse onto "body_chest" while BodyLegs
## maps to "body_legs"; "Ears" has no separate placeholder mesh and resolves
## onto "head" along with "Head" itself. Non-humanoid families build a single
## generic "body" part instead of the humanoid chest/legs split, so every body
## region collapses onto "body" there.
func _region_to_part(region: String, is_humanoid: bool) -> String:
	match region:
		"Hair", "HairTop":
			return "hair"
		"Beard":
			return "beard"
		"Head", "Ears":
			return "head"
		"BodyChest", "BodyShoulders", "BodyArms":
			return "body_chest" if is_humanoid else "body"
		"BodyLegs":
			return "body_legs" if is_humanoid else "body"
		_:
			return ""

# ---------------------------------------------------------------------------
# Visual construction (placeholder)
# ---------------------------------------------------------------------------

func _make_visual(instance_id: String, appearance: Dictionary) -> Dictionary:
	var rig := SkeletonRig.new()
	rig.name = "Character_%s" % instance_id
	var parts: Dictionary = {}

	var props: Dictionary = appearance.get("proportions", {})
	var height: float = props.get("height", 1.0)
	var mass: float = props.get("bodyMass", 1.0)
	var shoulder: float = props.get("shoulderWidth", 1.0)
	var head_scale: float = props.get("headScale", 1.0)

	var skin_idx: int = int(appearance.get("skinColor", 12))
	var hair_idx: int = int(appearance.get("hairColor", 40))
	var beard_idx: int = int(appearance.get("beardColor", 40))

	# Skeleton rig (Phase 20) — build a real Skeleton3D from the fabric
	# SkeletonDefinition so the character carries a bone hierarchy. Body and head
	# are skinned to their bones (torso / legs / head) so they deform with the
	# skeleton; hair/beard stay rig-root children (placeholder details) pending
	# real skinned assets; equipment attaches to sockets through the rig.
	var skeleton_res: Resource = GameData.SKELETONS.get(str(appearance.get("skeleton", DEFAULT_SKELETON)), null)
	rig.build(skeleton_res, props)
	var is_humanoid: bool = rig.get_family() == "humanoid"

	var torso_bone := _torso_bone(rig)
	var head_bone := rig.socket_to_bone("socket_head")
	if rig.get_bone_index(head_bone) == -1:
		head_bone = ""

	if is_humanoid:
		# Humanoid placeholders use the full body-shape landmark system (torso/
		# hip/head landmarks — characters.md §37.4), which only humanoid
		# skeletons declare `bodyShapeCoefficients` for.
		var landmarks: Dictionary = SkeletonRig.compute_landmarks(rig.get_body_shape_coefficients(), props)
		var torso_h: float = landmarks["torso_h"]
		var hip_y: float = landmarks["hip_y"]
		var head_size: float = landmarks["head_size"]
		var head_y: float = landmarks["head_y"]

		# Chest (torso/shoulders/arms region placeholder — §16 BodyChest/
		# BodyShoulders/BodyArms) — skinned to the torso bone so it deforms with the
		# skeleton. The mesh keeps its computed root-space position, expressed as a
		# bone-local offset (root-space minus the bone's rest origin) so the
		# rendered pose is unchanged at rest.
		var chest := _make_box(Vector3(0.55 * shoulder * mass, torso_h, 0.32 * mass), skin_idx)
		var chest_pos := Vector3(0.0, hip_y + torso_h * 0.5, 0.0)
		rig.attach_to_bone(torso_bone, chest, chest_pos - rig.get_bone_global_rest(torso_bone))
		parts["body_chest"] = { "node": chest, "min_lod": 3 }

		# Legs (hips-to-ground region placeholder — §16 BodyLegs) — skinned to the
		# hip bone so it deforms with the skeleton.
		var legs := _make_box(Vector3(0.45 * shoulder * mass, hip_y, 0.30 * mass), skin_idx)
		var legs_pos := Vector3(0.0, hip_y * 0.5, 0.0)
		var legs_bone := _legs_bone(rig)
		rig.attach_to_bone(legs_bone, legs, legs_pos - rig.get_bone_global_rest(legs_bone))
		parts["body_legs"] = { "node": legs, "min_lod": 3 }

		# Head — skinned to the head bone.
		var head := _make_box(Vector3(head_size, head_size, head_size), skin_idx)
		var head_pos := Vector3(0.0, head_y, 0.0)
		rig.attach_to_bone(head_bone, head, head_pos - rig.get_bone_global_rest(head_bone))
		parts["head"] = { "node": head, "min_lod": 3 }

		# Hair (independent component — §13).
		var hair_id: String = str(appearance.get("hair", "none"))
		if hair_id != "none" and hair_id != "":
			var hair := _make_box(Vector3(head_size * 1.05, head_size * 0.4, head_size * 1.05), hair_idx)
			hair.position = Vector3(0.0, head_y + head_size * 0.45, 0.0)
			rig.add_child(hair)
			parts["hair"] = { "node": hair, "min_lod": 1 }

		# Beard (independent component — §14).
		var beard_id: String = str(appearance.get("beard", "none"))
		if beard_id != "none" and beard_id != "":
			var beard := _make_box(Vector3(head_size * 0.7, head_size * 0.5, head_size * 0.25), beard_idx)
			beard.position = Vector3(0.0, head_y - head_size * 0.1, -head_size * 0.55)
			rig.add_child(beard)
			parts["beard"] = { "node": beard, "min_lod": 0 }
	else:
		# Non-humanoid families (quadruped/bird/serpent) don't declare
		# bodyShapeCoefficients and don't share the humanoid torso/hip/head
		# layout, so use a single generic body box and a generic head box,
		# sized from height/mass/headScale only and centered on their bone
		# (zero bone-local offset) rather than the humanoid landmark math.
		var body := _make_box(Vector3(0.5 * mass, height * 0.5, 0.5 * mass), skin_idx)
		rig.attach_to_bone(torso_bone, body, Vector3.ZERO)
		parts["body"] = { "node": body, "min_lod": 3 }

		var nh_head_size: float = 0.25 * head_scale
		var head := _make_box(Vector3(nh_head_size, nh_head_size, nh_head_size), skin_idx)
		rig.attach_to_bone(head_bone, head, Vector3.ZERO)
		parts["head"] = { "node": head, "min_lod": 3 }

	# Equipment — socket attachment with deformation modes (Phase 20 §10).
	var equipment: Dictionary = appearance.get("equipment", {})
	var eq_records: Dictionary = {}
	for slot in equipment:
		var entry: Dictionary = equipment[slot]
		var rec: Dictionary = _attach_equipment(rig, str(slot), entry, props)
		if rec.is_empty():
			continue
		eq_records[str(slot)] = rec
		parts[str(slot)] = { "node": rec["node"], "min_lod": int(rec["def"].get("minLodLevel", 0)) }

	var locomotion := Locomotion.new()

	return {
		"root":       rig,
		"rig":        rig,
		"parts":      parts,
		"equipment":  eq_records,
		"locomotion": locomotion,
	}

## Attach one equipment mesh to the rig for a slot + normalized entry, applying
## the item's deformation mode via the rig's socket system. Returns the
## equipment record { node, mode, socket, bone, item_id, def } ({} if the item
## is not equippable).
func _attach_equipment(rig, slot: String, entry: Dictionary, props: Dictionary) -> Dictionary:
	var def: Dictionary = _equipment_def(str(entry.get("item", "")))
	if def.is_empty():
		return {}
	var state: String = str(entry.get("state", "equipped"))
	var socket: String = _attachment_socket(def, state)
	var mode: String = str(def.get("deformationMode", "RIGID")).to_upper()
	var socket_pos: Vector3 = _socket_offset(rig, socket, props)
	# RIGID equipment sits at a fixed root-space socket offset (stays rigid).
	# SKINNED/HYBRID deform with the socket's bone, so their offset is the
	# socket position expressed in bone-local space (root-space minus the bone's
	# rest origin) — a bare root-space offset would double-apply once the mesh is
	# reparented under the bone.
	var offset: Vector3 = socket_pos
	if mode != "RIGID":
		offset = socket_pos - rig.get_bone_global_rest(rig.socket_to_bone(socket))
	var size: Vector3 = _vec3(def.get("size", [0.3, 0.3, 0.3]))
	var mesh := _make_box(size, _equipment_base_index(def, entry), _equipment_material_opts(def, entry))
	mesh.name = "Eq_%s" % slot
	rig.attach(socket, mesh, mode, offset)
	# RIGID equipment does not follow a bone — only SKINNED/HYBRID do.
	var bone: String = "" if mode == "RIGID" else rig.socket_to_bone(socket)
	return {
		"node":    mesh,
		"mode":    mode,
		"socket":  socket,
		"bone":    bone,
		"item_id": str(entry.get("item", "")),
		"def":     def,
	}

## Preferred torso bone to skin the body mesh to, in a family-agnostic order
## (humanoid/quadruped → Chest, bird → Spine, serpent → Spine_1, else Root).
## Returns "" when none exist, so the rig keeps the body a root child.
func _torso_bone(rig) -> String:
	for name in ["Chest", "Spine", "Spine_1", "Root"]:
		if rig.get_bone_index(name) != -1:
			return name
	return ""

## Preferred hip bone to skin the legs mesh to, in a family-agnostic order
## (humanoid/quadruped → Hips, else Root). Returns "" when none exist, so the
## rig keeps the legs mesh a root child.
func _legs_bone(rig) -> String:
	for name in ["Hips", "Root"]:
		if rig.get_bone_index(name) != -1:
			return name
	return ""

func _make_box(size: Vector3, palette_index: int, opts: Dictionary = {}) -> MeshInstance3D:
	var mesh := MeshInstance3D.new()
	var box := BoxMesh.new()
	box.size = size
	mesh.mesh = box
	# ONE shared ShaderMaterial for every part (§20): the palette index and
	# channel scalars are per-instance parameters, never a new material. The
	# shared body detail texture is bound once on the shared material (same for
	# all parts); per-part colour/channel values are written via
	# CharacterMaterial.apply_instance.
	var mat := CharacterMaterial.shared_material(_palette_colors())
	mat.set_shader_parameter("detail_tex", _get_body_texture())
	mesh.material_override = mat
	CharacterMaterial.apply_instance(mesh, palette_index, opts)
	return mesh

func _palette_colors() -> Array:
	if _palette.is_empty():
		_load_palette()
	return _palette

## Lazily decode the body-part texture once per slice instance. Cheap even if
## decoded again by a later instance — the point is not re-reading it per box.
func _get_body_texture() -> ImageTexture:
	if _body_texture == null:
		_body_texture = AssetOverlay.load_texture(AssetOverlay.PLACEHOLDER_REL)
	return _body_texture

## Resolve the socket for an equipment item's current attachment state (§7).
func _attachment_socket(def: Dictionary, state: String) -> String:
	var attachments: Dictionary = def.get("attachments", {})
	if attachments.has(state):
		return str(attachments[state])
	if attachments.has("equipped"):
		return str(attachments["equipped"])
	return "socket_back"

## Palette index that drives an equipment mesh's base colour (Phase 22): RIGID
## metal items resolve to a metals-region index (§21), otherwise the primary
## mask colour drives it (multi-mask-region rendering needs authored mask
## textures, deferred per §42). The deformation mode is normalised to upper case
## (fabric authors it as SKINNED/RIGID/HYBRID) and the metal branch is gated on
## the metal mask flag (masks.metal), consistent with the metalness channel.
func _equipment_base_index(def: Dictionary, entry: Dictionary) -> int:
	var mode: String = str(def.get("deformationMode", "RIGID")).to_upper()
	var metal: String = str(def.get("metal", "none"))
	var masks: Dictionary = def.get("masks", {})
	if mode == "RIGID" and bool(masks.get("metal", false)) and metal != "none" and metal != "":
		return _metal_palette_index(metal)
	if bool(masks.get("primary", false)):
		return int(entry.get("primaryColor", 0))
	if bool(masks.get("accent", false)):
		return int(entry.get("accentColor", 0))
	return int(entry.get("secondaryColor", 0))

## Per-instance channel opts for an equipment mesh (§21–§23): metalness from
## the metal mask flag (masks.metal), wear from the discrete durability tiers,
## roughness from the metal tone + wear, emission from the emission mask flag +
## per-item emissionColor palette index.
func _equipment_material_opts(def: Dictionary, entry: Dictionary) -> Dictionary:
	var metal: String = str(def.get("metal", "none"))
	var masks: Dictionary = def.get("masks", {})
	var durability: float = clampf(float(entry.get("durability", 1.0)), 0.0, 1.0)
	var metalness: float = 1.0 if bool(masks.get("metal", false)) else 0.0
	var wear := _wear_value(durability)
	var opts := {
		"primary_index":     int(entry.get("primaryColor", 0)),
		"secondary_index":   int(entry.get("secondaryColor", 0)),
		"accent_index":      int(entry.get("accentColor", 0)),
		"metalness":         metalness,
		"wear":              wear,
		"roughness":         _roughness_for(metal, wear, metalness),
		"emission_strength": 1.0 if bool(masks.get("emission", false)) else 0.0,
	}
	if bool(masks.get("emission", false)):
		opts["emission_index"] = _emission_index(def)
	return opts

## Metal tone → metals-region palette index (§21). The metals region bounds are
## read from the generated palette's `regions` field (palettes.js), not
## hardcoded; the within-region offset per tone is a content decision (dark
## ferrite → bright gold).
func _metal_palette_index(metal: String) -> int:
	var start: int = _region_bounds("metals")["start"]
	match metal:
		"iron", "ferrite":
			return start
		"steel", "veilsteel":
			return start + 16
		"bronze":
			return start + 24
		"gold":
			return start + 30
		_:
			return start + 8

## Emission colour is a palette index in the emission region (192–223, §22),
## read from the per-item emissionColor field, not a hardcoded RGB.
func _emission_index(def: Dictionary) -> int:
	var bounds := _region_bounds("emission")
	var idx := int(def.get("emissionColor", 200))
	return clampi(idx, int(bounds["start"]), int(bounds["end"]))

## Metal tone + wear → surface roughness (§21): different tones reflect light
## differently (iron rough, gold smooth) and wear roughens the surface.
func _roughness_for(metal: String, wear: float, metalness: float) -> float:
	var base := 0.55
	if metalness > 0.5:
		match metal:
			"iron", "ferrite":
				base = 0.55
			"steel", "veilsteel":
				base = 0.3
			"bronze":
				base = 0.4
			"gold":
				base = 0.2
			_:
				base = 0.5
	return clampf(base + wear * 0.35, 0.0, 1.0)

## Placeholder socket → local offset for the humanoid family, scaled by the
## current proportions via the same landmark formula the visual assembly and
## foot IK use (SkeletonRig.compute_landmarks), so sockets stay in sync with
## the body they dress. Real rigs define these per skeleton; this mapping
## keeps the code-only placeholder assembly coherent.
func _socket_offset(rig, socket: String, props: Dictionary) -> Vector3:
	# Non-humanoid skeletons declare no bodyShapeCoefficients and don't share the
	# humanoid landmark layout, so their sockets attach directly at their socket
	# bone's rest origin (characters.md §4) instead of humanoid landmark math
	# (which would place equipment on a body layout those families don't have).
	if rig.get_family() != "humanoid":
		return rig.get_bone_global_rest(rig.socket_to_bone(socket))
	var l: Dictionary = SkeletonRig.compute_landmarks(rig.get_body_shape_coefficients(), props)

	match socket:
		"socket_head", "socket_face":
			return Vector3(0.0, l["head_top"], 0.0)
		"socket_weapon_r":
			return Vector3(l["hand_x"], l["hand_y"], l["weapon_forward"])
		"socket_weapon_l":
			return Vector3(-l["hand_x"], l["hand_y"], l["weapon_forward"])
		"socket_shield":
			return Vector3(-l["hand_x"], l["hand_y"], 0.0)
		"socket_hip_r":
			return Vector3(l["hip_side"], l["hip_y"], 0.0)
		"socket_hip_l":
			return Vector3(-l["hip_side"], l["hip_y"], 0.0)
		"socket_back":
			return Vector3(0.0, l["chest_y"], l["back_forward"])
		"socket_cape":
			return Vector3(0.0, l["chest_y"] + l["cape_up"], l["back_forward"])
		"socket_chest":
			return Vector3(0.0, l["chest_y"], 0.0)
		_:
			return Vector3.ZERO

func _vec3(v) -> Vector3:
	if v is Vector3:
		return v
	if v is Array and v.size() >= 3:
		return Vector3(float(v[0]), float(v[1]), float(v[2]))
	return Vector3(0.3, 0.3, 0.3)
