extends Node
## Character slice — data-driven character appearance system (characters.md).
##
## Realizes the design doc as a working vertical slice:
##   - non-humanoid skeletons (humanoid / quadruped / bird / serpent)
##   - bones vs sockets, equipment slots vs sockets, attachment states
##   - body proportions with artistic bounds, mesh hiding, deformation modes
##   - a single 256-entry palette with color indices instead of raw RGB
##   - persistence-as-recipe + multiplayer visual state + derived wear
##   - LOD via per-attachment minLodLevel
##
## Definitions come from GameData (the generated autoload) — skeletons, the
## palette, and appearance recipes live in the fabric
## (fabric/gameplay/characters/*) and are generated by `newel generate`, while
## equipment-visual fields live on the equippable items in GameData.ITEMS. This
## slice only assembles visuals and normalizes recipes; it never hardcodes
## content. The fabric is the single source of truth.
##
## Visuals are modular low-poly placeholders (BoxMesh parts) assembled in code —
## real meshes / textures / skeletons / animations are asset-production work
## outside this slice's scope. See characters.md §37 for the animation system
## (not yet specified).
##
## Plug contract (GameBus signals consumed / emitted):
##   OUT : character_spawned(instance_id, skeleton_id, position)
##         character_appearance_changed(instance_id, appearance)
##
## Public API:
##   create_character(appearance_id, pos)                  -> String (instance_id or "")
##   create_character_from_recipe(recipe, pos)             -> String
##   apply_appearance(instance_id, recipe)                 -> bool
##   get_appearance(instance_id)                           -> Dictionary
##   get_visual_state(instance_id)                         -> Dictionary
##   serialize_appearance(recipe)                          -> Dictionary
##   deserialize_appearance(data)                          -> Dictionary
##   palette_color(index)                                  -> Color
##   get_palette_size()                                    -> int
##   set_lod(level) / get_lod()                            -> void / int
##   is_part_visible(instance_id, part_key)                -> bool

const Locomotion  := preload("res://src/character/locomotion.gd")
const SkeletonRig := preload("res://src/character/skeleton_rig.gd")
const GameDataReader := preload("res://src/core/game_data_reader.gd")

const MIN_LOD := 0
const MAX_LOD := 3

## Palette is a fixed 256 entries (§19): one byte per color index.
const PALETTE_SIZE := 256
const PALETTE_KEY := "DefaultPalette"
const DEFAULT_SKELETON := "HumanoidSkeleton"

## Body-proportion bounds (characters.md §8). Artistic, not engine defaults —
## each combination must survive validation against animations, clothing and
## clipping before finalizing. Kept here as mechanics config (clamping bounds);
## the fabric carries the enumerable content (skeletons, palettes, appearances,
## equipment).
const BODY_PROP_BOUNDS: Dictionary = {
	"height":        { "min": 0.85, "default": 1.00, "max": 1.15 },
	"bodyMass":      { "min": 0.80, "default": 1.00, "max": 1.20 },
	"shoulderWidth": { "min": 0.90, "default": 1.00, "max": 1.10 },
	"armLength":     { "min": 0.90, "default": 1.00, "max": 1.10 },
	"legLength":     { "min": 0.90, "default": 1.00, "max": 1.10 },
	"headScale":     { "min": 0.90, "default": 1.00, "max": 1.10 },
}

## Instance record: { "appearance", "position", "root", "parts" }.
var _instances: Dictionary = {}
var _next_id: int = 0
var _lod: int = 0
var _palette: Array = []

## Instance id of the player's own character avatar (set by game_root) — the
## target for combat- and death-driven animation triggers.
var _player_character_id: String = ""

func _ready() -> void:
	_load_palette()
	GameBus.character_attack_requested.connect(_on_attack_requested)
	GameBus.character_death_requested.connect(_on_death_requested)

# ---------------------------------------------------------------------------
# Public — creation
# ---------------------------------------------------------------------------

## Spawn a character from a named appearance recipe in GameData.APPEARANCES.
## Returns the instance_id, or "" if the appearance_id is unknown.
func create_character(appearance_id: String, pos: Vector3) -> String:
	var res: Resource = GameData.APPEARANCES.get(appearance_id, null)
	if res == null:
		push_warning("CharacterSlice: unknown appearance_id '%s'" % appearance_id)
		return ""
	return create_character_from_recipe(_appearance_to_recipe(res), pos)

## Spawn a character from a raw appearance recipe (persisted / network source).
## The recipe is normalized (unknown fields dropped, proportions clamped) before
## the visual is assembled.
func create_character_from_recipe(recipe: Dictionary, pos: Vector3) -> String:
	var normalized := deserialize_appearance(recipe)
	var iid := "character_%d" % _next_id
	_next_id += 1

	var built: Dictionary = _make_visual(iid, normalized)
	var root: Node3D = built["root"]
	root.position = pos
	add_child(root)

	_instances[iid] = {
		"appearance": normalized,
		"position":   pos,
		"root":       root,
		"rig":        built["rig"],
		"locomotion": built["locomotion"],
		"equipment":  built["equipment"],
		"parts":      built["parts"],
	}
	_apply_lod(iid)

	var skeleton_id: String = str(normalized.get("skeleton", "?"))
	GameBus.character_spawned.emit(iid, skeleton_id, pos)
	print("CharacterSlice: spawned %s [%s] at %s" % [skeleton_id, iid, pos])
	return iid

## Replace an existing instance's appearance recipe (rebuilds the visual).
func apply_appearance(instance_id: String, recipe: Dictionary) -> bool:
	if not _instances.has(instance_id):
		return false
	var normalized := deserialize_appearance(recipe)
	var inst: Dictionary = _instances[instance_id]

	var old_root: Node3D = inst["root"]
	old_root.queue_free()

	var built: Dictionary = _make_visual(instance_id, normalized)
	var root: Node3D = built["root"]
	root.position = inst["position"]
	add_child(root)

	inst["appearance"] = normalized
	inst["root"] = root
	inst["rig"] = built["rig"]
	inst["locomotion"] = built["locomotion"]
	inst["equipment"] = built["equipment"]
	inst["parts"] = built["parts"]
	_apply_lod(instance_id)

	GameBus.character_appearance_changed.emit(instance_id, normalized)
	return true

# ---------------------------------------------------------------------------
# Public — queries
# ---------------------------------------------------------------------------

## Return the normalized appearance recipe for an instance (deep copy).
func get_appearance(instance_id: String) -> Dictionary:
	if not _instances.has(instance_id):
		return {}
	return _instances[instance_id]["appearance"].duplicate(true)

## Assemble the multiplayer visual state (characters.md §32). Derived visual
## state (wear from durability, §23/§33) is computed here and NOT persisted.
func get_visual_state(instance_id: String) -> Dictionary:
	var appearance := get_appearance(instance_id)
	if appearance.is_empty():
		return {}

	var equipment: Dictionary = {}
	var eq_dict: Dictionary = appearance.get("equipment", {})
	for slot in eq_dict:
		var entry: Dictionary = eq_dict[slot]
		equipment[slot] = entry.duplicate(true)
		equipment[slot]["wear"] = _wear_level(float(entry.get("durability", 1.0)))

	return {
		"identity": { "skeleton": appearance.get("skeleton", ""), "body": appearance.get("body", "") },
		"body":     { "proportions": appearance.get("proportions", {}), "skinColor": appearance.get("skinColor", 0) },
		"face":     { "head": appearance.get("head", ""), "eyes": appearance.get("eyes", ""), "eyeColor": appearance.get("eyeColor", 0), "beard": appearance.get("beard", "") },
		"hair":     { "asset": appearance.get("hair", ""), "color": appearance.get("hairColor", 0) },
		"equipment": equipment,
	}

## Whether a named part (e.g. "hair", "Chest") is currently visible under the
## active LOD. Exposed for debug/HUD and tests.
func is_part_visible(instance_id: String, part_key: String) -> bool:
	if not _instances.has(instance_id):
		return false
	var parts: Dictionary = _instances[instance_id]["parts"]
	if not parts.has(part_key):
		return false
	return parts[part_key]["node"].visible

## Live node for a named part (body/head/hair/beard or an equipment slot), or
## null when the part is absent. Exposed for tests and the debug HUD.
func get_part_node(instance_id: String, part_key: String) -> Node3D:
	if not _instances.has(instance_id):
		return null
	var parts: Dictionary = _instances[instance_id]["parts"]
	if not parts.has(part_key):
		return null
	return parts[part_key].get("node", null)

# ---------------------------------------------------------------------------
# Public — recipe (de)serialization (characters.md §30, §31)
# ---------------------------------------------------------------------------

## A recipe is already JSON-safe (String / int / float / Dictionary / Array).
## Return a deep copy so callers cannot mutate live instance state.
func serialize_appearance(recipe: Dictionary) -> Dictionary:
	return recipe.duplicate(true)

## Normalize a recipe: validate skeleton against GameData.SKELETONS, clamp
## proportions to artistic bounds, clamp color indices to [0, PALETTE_SIZE), and
## drop equipment whose item is not an equippable entry in GameData.ITEMS.
func deserialize_appearance(data: Dictionary) -> Dictionary:
	var recipe: Dictionary = {}

	var skeleton: String = str(data.get("skeleton", DEFAULT_SKELETON))
	if not GameData.SKELETONS.has(skeleton):
		skeleton = DEFAULT_SKELETON
	recipe["skeleton"] = skeleton

	recipe["body"] = str(data.get("body", "human_body_01"))
	recipe["proportions"] = _normalize_proportions(data.get("proportions", {}))

	recipe["skinColor"] = _color_index(data.get("skinColor", 12))
	recipe["head"] = str(data.get("head", "head_01"))
	recipe["eyes"] = str(data.get("eyes", "eyes_01"))
	recipe["eyeColor"] = _color_index(data.get("eyeColor", 225))
	recipe["hair"] = str(data.get("hair", "hair_short_01"))
	recipe["hairColor"] = _color_index(data.get("hairColor", 40))
	recipe["beard"] = str(data.get("beard", "beard_none"))
	recipe["beardColor"] = _color_index(data.get("beardColor", 40))

	var eq_raw = data.get("equipment", {})
	var eq_out: Dictionary = {}
	if eq_raw is Dictionary:
		var eq_in: Dictionary = eq_raw
		for slot in eq_in:
			var entry = eq_in[slot]
			if entry is Dictionary:
				var item_id: String = str(entry.get("item", ""))
				if not _equipment_def(item_id).is_empty():
					eq_out[slot] = _normalize_equipment(entry)
	recipe["equipment"] = eq_out

	return recipe

# ---------------------------------------------------------------------------
# Public — palette (characters.md §19)
# ---------------------------------------------------------------------------

## Return the color at a palette index (clamped to [0, PALETTE_SIZE)).
func palette_color(index: int) -> Color:
	if _palette.is_empty():
		_load_palette()
	if _palette.is_empty():
		return Color.WHITE
	return _palette[clampi(index, 0, _palette.size() - 1)]

func get_palette_size() -> int:
	if _palette.is_empty():
		_load_palette()
	return _palette.size()

# ---------------------------------------------------------------------------
# Public — LOD (characters.md §35, §36)
# ---------------------------------------------------------------------------

func set_lod(level: int) -> void:
	_lod = clampi(level, MIN_LOD, MAX_LOD)
	for iid in _instances:
		_apply_lod(iid)

func get_lod() -> int:
	return _lod

# ---------------------------------------------------------------------------
# Public — equipment + animation (ROADMAP Phase 20)
# ---------------------------------------------------------------------------

## Equip an item onto a character slot (replaces any existing equipment there).
## `item_key` is a GameData.ITEMS key; `state` is the attachment state
## (equipped/sheathed/stored/hidden). Returns true on success.
func apply_equipment(instance_id: String, slot: String, item_key: String, state: String = "equipped") -> bool:
	if not _instances.has(instance_id):
		return false
	var inst: Dictionary = _instances[instance_id]
	var rig = inst["rig"]
	var props: Dictionary = inst["appearance"].get("proportions", {})

	var entry := {
		"item": item_key,
		"state": state,
		"durability": 1.0,
	}
	var rec: Dictionary = _attach_equipment(rig, slot, entry, props)
	if rec.is_empty():
		return false

	# Replace any existing mesh on the slot.
	var equipment: Dictionary = inst["equipment"]
	if equipment.has(slot):
		var old: Dictionary = equipment[slot]
		var old_node: Node3D = old.get("node", null)
		if old_node != null:
			old_node.queue_free()

	equipment[slot] = rec
	inst["parts"][slot] = { "node": rec["node"], "min_lod": int(rec["def"].get("minLodLevel", 0)) }

	# Reflect the change in the appearance recipe so persistence / visual state
	# stay consistent with the live instance.
	var app: Dictionary = inst["appearance"]
	var eq: Dictionary = app.get("equipment", {})
	eq[slot] = entry
	app["equipment"] = eq
	_apply_lod(instance_id)
	GameBus.character_appearance_changed.emit(instance_id, app)
	return true

## Unequip a slot (free the mesh and drop it from the appearance recipe).
func clear_equipment(instance_id: String, slot: String) -> bool:
	if not _instances.has(instance_id):
		return false
	var inst: Dictionary = _instances[instance_id]
	var equipment: Dictionary = inst["equipment"]
	if not equipment.has(slot):
		return false
	var rec: Dictionary = equipment[slot]
	var node: Node3D = rec.get("node", null)
	if node != null:
		node.queue_free()
	equipment.erase(slot)
	if inst["parts"].has(slot):
		inst["parts"].erase(slot)
	var app: Dictionary = inst["appearance"]
	if app.has("equipment"):
		var eq: Dictionary = app["equipment"]
		if eq.has(slot):
			eq.erase(slot)
	GameBus.character_appearance_changed.emit(instance_id, app)
	return true

## Advance the locomotion state machine for an instance. Returns the resulting
## Locomotion.State int, and emits character_state_changed on any transition.
func update_locomotion(instance_id: String, speed: float, grounded: bool, velocity_y: float, delta: float) -> int:
	if not _instances.has(instance_id):
		return -1
	var loco = _instances[instance_id]["locomotion"]
	var before: int = loco.get_state()
	var after: int = loco.update(speed, grounded, velocity_y, delta)
	if after != before:
		GameBus.character_state_changed.emit(instance_id, loco.state_name())
	return after

func get_locomotion_state(instance_id: String) -> int:
	if not _instances.has(instance_id):
		return -1
	return _instances[instance_id]["locomotion"].get_state()

func get_locomotion_state_name(instance_id: String) -> String:
	if not _instances.has(instance_id):
		return ""
	return _instances[instance_id]["locomotion"].state_name()

## Play the attack animation on an instance (transient ATTACK state).
func trigger_attack(instance_id: String) -> void:
	if not _instances.has(instance_id):
		return
	_instances[instance_id]["locomotion"].trigger_attack()

## Play the death animation on an instance (terminal DEATH state).
func trigger_death(instance_id: String) -> void:
	if not _instances.has(instance_id):
		return
	_instances[instance_id]["locomotion"].trigger_death()

## Foot IK targets for an instance. `terrain_height` is a Callable(Vector2)→float.
func get_foot_ik_targets(instance_id: String, terrain_height: Callable) -> Dictionary:
	if not _instances.has(instance_id):
		return {}
	var inst: Dictionary = _instances[instance_id]
	var props: Dictionary = inst["appearance"].get("proportions", {})
	var height: float = props.get("height", 1.0)
	var leg_len: float = props.get("legLength", 1.0)
	var hip_height := 0.38 * leg_len * height
	var leg_length := 0.38 * leg_len * height + 0.05
	return SkeletonRig.compute_foot_targets(
		terrain_height,
		inst["position"],
		hip_height,
		leg_length,
		0.12 * height,
		0.0
	)

## Bone names of the instance's skeleton (ordered, parents first).
func get_skeleton_bone_names(instance_id: String) -> Array:
	if not _instances.has(instance_id):
		return []
	return _instances[instance_id]["rig"].get_bone_names()

## Deformation mode recorded for an equipped slot ("" if not equipped).
func get_equipment_deformation_mode(instance_id: String, slot: String) -> String:
	if not _instances.has(instance_id):
		return ""
	var equipment: Dictionary = _instances[instance_id]["equipment"]
	if not equipment.has(slot):
		return ""
	return str(equipment[slot].get("mode", ""))

## Which bone an equipped slot attaches to ("" for RIGID / unattached).
func get_equipment_attached_bone(instance_id: String, slot: String) -> String:
	if not _instances.has(instance_id):
		return ""
	var equipment: Dictionary = _instances[instance_id]["equipment"]
	if not equipment.has(slot):
		return ""
	return str(equipment[slot].get("bone", ""))

## Designate the player's own character avatar (drives combat/death animation).
func set_player_character(instance_id: String) -> void:
	_player_character_id = instance_id

func get_player_character() -> String:
	return _player_character_id

func _on_attack_requested(instance_id: String) -> void:
	trigger_attack(instance_id)

func _on_death_requested(instance_id: String) -> void:
	trigger_death(instance_id)

## Build the equipment-visual definition for an item from GameData.ITEMS.
## Returns {} when the item is missing or has no equipment slot (not equippable).
## `hide` and `compatibleTags` exist in the fabric but are not yet consumed by
## the placeholder visual.
func _equipment_def(item_id: String) -> Dictionary:
	var res: Resource = GameData.ITEMS.get(item_id, null)
	if res == null:
		return {}
	var slot := GameDataReader.str_field(res, "equipmentSlot", "")
	if slot == "":
		return {}
	return {
		"slot":           slot,
		"deformationMode": GameDataReader.str_field(res, "deformationMode", "RIGID"),
		"masks":           GameDataReader.json_field(res, "masks", {}),
		"attachments":     GameDataReader.json_field(res, "attachments", {}),
		"minLodLevel":     GameDataReader.int_field(res, "minLodLevel", 0),
		"size":            GameDataReader.json_field(res, "size", [0.3, 0.3, 0.3]),
		"metal":           GameDataReader.str_field(res, "metalTone", "none"),
	}

## Build a raw appearance recipe Dictionary from a GameData.APPEARANCES resource.
func _appearance_to_recipe(res: Resource) -> Dictionary:
	return {
		"skeleton":    GameDataReader.str_field(res, "skeleton", DEFAULT_SKELETON),
		"body":        GameDataReader.str_field(res, "body", "human_body_01"),
		"proportions": GameDataReader.json_field(res, "proportions", {}),
		"skinColor":   GameDataReader.int_field(res, "skinColor", 12),
		"head":        GameDataReader.str_field(res, "head", "head_01"),
		"eyes":        GameDataReader.str_field(res, "eyes", "eyes_01"),
		"eyeColor":    GameDataReader.int_field(res, "eyeColor", 225),
		"hair":        GameDataReader.str_field(res, "hair", "hair_short_01"),
		"hairColor":   GameDataReader.int_field(res, "hairColor", 40),
		"beard":       GameDataReader.str_field(res, "beard", "beard_none"),
		"beardColor":  GameDataReader.int_field(res, "beardColor", 40),
		"equipment":   GameDataReader.json_field(res, "equipment", {}),
	}

# ---------------------------------------------------------------------------
# Palette construction
# ---------------------------------------------------------------------------

func _load_palette() -> void:
	var res: Resource = GameData.PALETTES.get(PALETTE_KEY, null)
	var entries = GameDataReader.json_field(res, "entries", []) if res != null else []
	_palette = []
	if entries is Array and entries.size() > 0:
		for hex_str in entries:
			_palette.append(Color(str(hex_str)))
	else:
		_palette = _fallback_palette()

## Neutral grayscale fallback so placeholder colors still resolve if the
## generated palette resource is unavailable.
func _fallback_palette() -> Array:
	var out: Array = []
	for i in range(PALETTE_SIZE):
		var g := float(i) / float(PALETTE_SIZE - 1)
		out.append(Color(g, g, g))
	return out

# ---------------------------------------------------------------------------
# Recipe normalization helpers
# ---------------------------------------------------------------------------

func _normalize_proportions(props) -> Dictionary:
	var src: Dictionary = props if props is Dictionary else {}
	var out: Dictionary = {}
	for key in BODY_PROP_BOUNDS:
		var bounds: Dictionary = BODY_PROP_BOUNDS[key]
		var lo: float = bounds["min"]
		var hi: float = bounds["max"]
		var def: float = bounds["default"]
		var v = src.get(key, def)
		if v is float or v is int:
			out[key] = clampf(float(v), lo, hi)
		else:
			out[key] = def
	return out

func _color_index(v) -> int:
	if v is float or v is int:
		return clampi(int(v), 0, PALETTE_SIZE - 1)
	return 0

func _normalize_equipment(entry: Dictionary) -> Dictionary:
	return {
		"item":           str(entry.get("item", "")),
		"state":          str(entry.get("state", "equipped")),
		"primaryColor":   _color_index(entry.get("primaryColor", 0)),
		"secondaryColor": _color_index(entry.get("secondaryColor", 0)),
		"accentColor":    _color_index(entry.get("accentColor", 0)),
		"durability":     clampf(float(entry.get("durability", 1.0)), 0.0, 1.0),
	}

## Wear is derived from durability, never persisted (§23).
func _wear_level(durability: float) -> String:
	if durability >= 0.9:
		return "New"
	if durability >= 0.6:
		return "Used"
	if durability >= 0.3:
		return "Worn"
	return "Heavily Damaged"

# ---------------------------------------------------------------------------
# LOD
# ---------------------------------------------------------------------------

## A part renders while `_lod <= part.min_lod`. Body/head carry the highest
## min_lod (always visible); fine details (beard, hair) carry the lowest.
func _apply_lod(instance_id: String) -> void:
	if not _instances.has(instance_id):
		return
	var parts: Dictionary = _instances[instance_id]["parts"]
	for key in parts:
		var part: Dictionary = parts[key]
		var node: Node3D = part["node"]
		var min_lod: int = part.get("min_lod", 0)
		node.visible = _lod <= min_lod

# ---------------------------------------------------------------------------
# Visual construction (placeholder)
# ---------------------------------------------------------------------------

func _make_visual(instance_id: String, appearance: Dictionary) -> Dictionary:
	var rig := SkeletonRig.new()
	rig.name = "Character_%s" % instance_id
	var parts: Dictionary = {}

	var props: Dictionary = appearance.get("proportions", {})
	var height: float = props.get("height", 1.0)
	var mass: float = props.get("bodyMass", 1.0)
	var shoulder: float = props.get("shoulderWidth", 1.0)
	var head_scale: float = props.get("headScale", 1.0)
	var leg_len: float = props.get("legLength", 1.0)

	var skin: Color = palette_color(int(appearance.get("skinColor", 12)))
	var hair_color: Color = palette_color(int(appearance.get("hairColor", 40)))
	var beard_color: Color = palette_color(int(appearance.get("beardColor", 40)))

	var torso_h := 0.62 * height
	var hip_y := 0.38 * leg_len * height
	var head_size := 0.30 * head_scale
	var head_y := hip_y + torso_h + head_size * 0.5

	# Skeleton rig (Phase 20) — build a real Skeleton3D from the fabric
	# SkeletonDefinition so the character carries a bone hierarchy. Body and head
	# are skinned to their bones (torso / head) so they deform with the
	# skeleton; hair/beard stay rig-root children (placeholder details) pending
	# real skinned assets; equipment attaches to sockets through the rig.
	var skeleton_res: Resource = GameData.SKELETONS.get(str(appearance.get("skeleton", DEFAULT_SKELETON)), null)
	rig.build(skeleton_res, height)

	# Body (torso + legs as one block placeholder) — skinned to the torso bone so
	# it deforms with the skeleton. The mesh keeps its computed root-space
	# position, expressed as a bone-local offset (root-space minus the bone's
	# rest origin) so the rendered pose is unchanged at rest.
	var body := _make_box(Vector3(0.55 * shoulder * mass, torso_h, 0.32 * mass), skin)
	var body_pos := Vector3(0.0, hip_y + torso_h * 0.5, 0.0)
	var torso_bone := _torso_bone(rig)
	rig.attach_to_bone(torso_bone, body, body_pos - rig.get_bone_global_rest(torso_bone))
	parts["body"] = { "node": body, "min_lod": 3 }

	# Head — skinned to the head bone.
	var head := _make_box(Vector3(head_size, head_size, head_size), skin)
	var head_pos := Vector3(0.0, head_y, 0.0)
	var head_bone := rig.socket_to_bone("socket_head")
	if rig.get_bone_index(head_bone) == -1:
		head_bone = ""
	rig.attach_to_bone(head_bone, head, head_pos - rig.get_bone_global_rest(head_bone))
	parts["head"] = { "node": head, "min_lod": 3 }

	# Hair (independent component — §13).
	var hair_id: String = str(appearance.get("hair", "none"))
	if hair_id != "none" and hair_id != "":
		var hair := _make_box(Vector3(head_size * 1.05, head_size * 0.4, head_size * 1.05), hair_color)
		hair.position = Vector3(0.0, head_y + head_size * 0.45, 0.0)
		rig.add_child(hair)
		parts["hair"] = { "node": hair, "min_lod": 1 }

	# Beard (independent component — §14).
	var beard_id: String = str(appearance.get("beard", "none"))
	if beard_id != "none" and beard_id != "":
		var beard := _make_box(Vector3(head_size * 0.7, head_size * 0.5, head_size * 0.25), beard_color)
		beard.position = Vector3(0.0, head_y - head_size * 0.1, -head_size * 0.55)
		rig.add_child(beard)
		parts["beard"] = { "node": beard, "min_lod": 0 }

	# Equipment — socket attachment with deformation modes (Phase 20 §10).
	var equipment: Dictionary = appearance.get("equipment", {})
	var eq_records: Dictionary = {}
	for slot in equipment:
		var entry: Dictionary = equipment[slot]
		var rec: Dictionary = _attach_equipment(rig, str(slot), entry, props)
		if rec.is_empty():
			continue
		eq_records[str(slot)] = rec
		parts[str(slot)] = { "node": rec["node"], "min_lod": int(rec["def"].get("minLodLevel", 0)) }

	var locomotion := Locomotion.new()

	return {
		"root":       rig,
		"rig":        rig,
		"parts":      parts,
		"equipment":  eq_records,
		"locomotion": locomotion,
	}

## Attach one equipment mesh to the rig for a slot + normalized entry, applying
## the item's deformation mode via the rig's socket system. Returns the
## equipment record { node, mode, socket, bone, item_id, def } ({} if the item
## is not equippable).
func _attach_equipment(rig, slot: String, entry: Dictionary, props: Dictionary) -> Dictionary:
	var def: Dictionary = _equipment_def(str(entry.get("item", "")))
	if def.is_empty():
		return {}
	var state: String = str(entry.get("state", "equipped"))
	var socket: String = _attachment_socket(def, state)
	var mode: String = str(def.get("deformationMode", "RIGID")).to_upper()
	var socket_pos: Vector3 = _socket_offset(socket, props)
	# RIGID equipment sits at a fixed root-space socket offset (stays rigid).
	# SKINNED/HYBRID deform with the socket's bone, so their offset is the
	# socket position expressed in bone-local space (root-space minus the bone's
	# rest origin) — a bare root-space offset would double-apply once the mesh is
	# reparented under the bone.
	var offset: Vector3 = socket_pos
	if mode != "RIGID":
		offset = socket_pos - rig.get_bone_global_rest(rig.socket_to_bone(socket))
	var eq_color: Color = _equipment_color(def, entry)
	var size: Vector3 = _vec3(def.get("size", [0.3, 0.3, 0.3]))
	var mesh := _make_box(size, eq_color)
	mesh.name = "Eq_%s" % slot
	rig.attach(socket, mesh, mode, offset)
	# RIGID equipment does not follow a bone — only SKINNED/HYBRID do.
	var bone: String = "" if mode == "RIGID" else rig.socket_to_bone(socket)
	return {
		"node":    mesh,
		"mode":    mode,
		"socket":  socket,
		"bone":    bone,
		"item_id": str(entry.get("item", "")),
		"def":     def,
	}

## Preferred torso bone to skin the body mesh to, in a family-agnostic order
## (humanoid/quadruped → Chest, bird → Spine, serpent → Spine_1, else Root).
## Returns "" when none exist, so the rig keeps the body a root child.
func _torso_bone(rig) -> String:
	for name in ["Chest", "Spine", "Spine_1", "Root"]:
		if rig.get_bone_index(name) != -1:
			return name
	return ""

func _make_box(size: Vector3, color: Color) -> MeshInstance3D:
	var mesh := MeshInstance3D.new()
	var box := BoxMesh.new()
	box.size = size
	mesh.mesh = box
	var mat := StandardMaterial3D.new()
	mat.albedo_color = color
	# Pixel-art aesthetic lives at the asset level (Point filtering, low-res
	# textures, palettes), not in post-processing (§29). The placeholder uses
	# flat albedo until real assets exist.
	mesh.material_override = mat
	return mesh

## Resolve the socket for an equipment item's current attachment state (§7).
func _attachment_socket(def: Dictionary, state: String) -> String:
	var attachments: Dictionary = def.get("attachments", {})
	if attachments.has(state):
		return str(attachments[state])
	if attachments.has("equipped"):
		return str(attachments["equipped"])
	return "socket_back"

## Placeholder equipment color: RIGID metal items take the metal tone; otherwise
## the primary mask drives the color (multi-mask-region rendering needs real
## assets, deferred per §42).
func _equipment_color(def: Dictionary, entry: Dictionary) -> Color:
	var mode: String = str(def.get("deformationMode", "RIGID"))
	var metal: String = str(def.get("metal", "none"))
	if mode == "RIGID" and metal != "none" and metal != "":
		return _metal_color(metal)
	var masks: Dictionary = def.get("masks", {})
	if masks.get("primary", false):
		return palette_color(int(entry.get("primaryColor", 0)))
	if masks.get("accent", false):
		return palette_color(int(entry.get("accentColor", 0)))
	return palette_color(int(entry.get("secondaryColor", 0)))

func _metal_color(metal: String) -> Color:
	match metal:
		"iron", "ferrite":
			return Color(0.62, 0.62, 0.66)
		"steel", "veilsteel":
			return Color(0.72, 0.76, 0.82)
		"bronze":
			return Color(0.72, 0.55, 0.35)
		"gold":
			return Color(0.95, 0.78, 0.32)
		_:
			return Color(0.7, 0.7, 0.72)

## Placeholder socket → local offset for the humanoid family, scaled by the
## current proportions. Real rigs define these per skeleton; this mapping keeps
## the code-only placeholder assembly coherent.
func _socket_offset(socket: String, props: Dictionary) -> Vector3:
	var height: float = props.get("height", 1.0)
	var shoulder: float = props.get("shoulderWidth", 1.0)
	var leg_len: float = props.get("legLength", 1.0)
	var head_scale: float = props.get("headScale", 1.0)
	var arm_len: float = props.get("armLength", 1.0)

	var torso_h := 0.62 * height
	var hip_y := 0.38 * leg_len * height
	var chest_y := hip_y + torso_h * 0.6
	var head_size := 0.30 * head_scale
	var head_top := hip_y + torso_h + head_size
	var hand_x := 0.42 * shoulder
	var hand_y := chest_y - 0.05 * arm_len * height

	match socket:
		"socket_head", "socket_face":
			return Vector3(0.0, head_top, 0.0)
		"socket_weapon_r":
			return Vector3(hand_x, hand_y, 0.15)
		"socket_weapon_l":
			return Vector3(-hand_x, hand_y, 0.15)
		"socket_shield":
			return Vector3(-hand_x, hand_y, 0.0)
		"socket_hip_r":
			return Vector3(0.2, hip_y, 0.0)
		"socket_hip_l":
			return Vector3(-0.2, hip_y, 0.0)
		"socket_back":
			return Vector3(0.0, chest_y, -0.25)
		"socket_cape":
			return Vector3(0.0, chest_y + 0.15, -0.25)
		"socket_chest":
			return Vector3(0.0, chest_y, 0.0)
		_:
			return Vector3.ZERO

func _vec3(v) -> Vector3:
	if v is Vector3:
		return v
	if v is Array and v.size() >= 3:
		return Vector3(float(v[0]), float(v[1]), float(v[2]))
	return Vector3(0.3, 0.3, 0.3)
