# @generated by @newel/generator-godot — do not edit
class_name CinderGargoyleData
extends Resource

enum Tier {
	TIER_1,
	TIER_2,
	TIER_3,
	TIER_4,
	TIER_5,
}

enum AggressionLevel {
	PASSIVE,
	NEUTRAL,
	AGGRESSIVE,
	TERRITORIAL,
}

enum Biome {
	TEMPERATE_FOREST,
	TEMPERATE_GRASSLAND,
	VOLCANIC_BADLANDS,
	TWILIGHT_GROVE,
	VOID_RIFT,
}

enum State {
	IDLE,
	ALERT,
	AGGRESSIVE,
	FLEEING,
	DEAD,
	RESPAWNING,
}
