# @generated by @newel/generator-godot — do not edit
# IR version: 3.0.0
extends Resource
class_name ForestBoarData

enum Tier {
	TIER_1,
	TIER_2,
	TIER_3,
	TIER_4,
	TIER_5,
}

enum AggressionLevel {
	PASSIVE,
	NEUTRAL,
	AGGRESSIVE,
	TERRITORIAL,
}

enum State {
	IDLE,
	ALERT,
	AGGRESSIVE,
	FLEEING,
	DEAD,
	RESPAWNING,
}
