# @generated by @newel/generator-godot — do not edit
class_name LavaSlugData
extends Resource

enum Tier {
	TIER_1,
	TIER_2,
	TIER_3,
	TIER_4,
	TIER_5,
}

enum AggressionLevel {
	PASSIVE,
	NEUTRAL,
	AGGRESSIVE,
	TERRITORIAL,
}

enum Biome {
	TEMPERATE_FOREST,
	TEMPERATE_GRASSLAND,
	VOLCANIC_BADLANDS,
	TWILIGHT_GROVE,
	VOID_RIFT,
}

enum State {
	IDLE,
	ALERT,
	AGGRESSIVE,
	FLEEING,
	DEAD,
	RESPAWNING,
}

@export var id: String
@export var state: int
@export var tier: int
@export var aggressionLevel: int
@export var baseHp: int
@export var baseDamage: int
@export var alertRadius: float
@export var attackRadius: float
@export var fleeThreshold: float
@export var respawnSeconds: int
@export var spawnCount: int
@export var biome: int
@export var drops: Array
