# @generated by @newel/generator-godot — do not edit
class_name LavaSlugData
extends Resource

enum Tier {
	TIER_1,
	TIER_2,
	TIER_3,
	TIER_4,
	TIER_5,
}

enum AggressionLevel {
	PASSIVE,
	NEUTRAL,
	AGGRESSIVE,
	TERRITORIAL,
}

enum State {
	IDLE,
	ALERT,
	AGGRESSIVE,
	FLEEING,
	DEAD,
	RESPAWNING,
}

@export var id: String
@export var state: int
@export var tier: int
@export var aggressionLevel: int
@export var baseHp: int
@export var baseDamage: int
