# @generated by @newel/generator-godot — do not edit
extends Resource
class_name RiftWardenData

enum Tier {
	TIER_1,
	TIER_2,
	TIER_3,
	TIER_4,
	TIER_5,
}

enum Aggressionlevel {
	PASSIVE,
	NEUTRAL,
	AGGRESSIVE,
	TERRITORIAL,
}

enum State {
	IDLE,
	AGGRESSIVE,
	DEAD,
	RESPAWNING,
}
