# @generated by @newel/generator-godot — do not edit
class_name RiftWardenData
extends Resource

enum Tier {
	TIER_1,
	TIER_2,
	TIER_3,
	TIER_4,
	TIER_5,
}

enum AggressionLevel {
	PASSIVE,
	NEUTRAL,
	AGGRESSIVE,
	TERRITORIAL,
}

enum State {
	IDLE,
	AGGRESSIVE,
	DEAD,
	RESPAWNING,
}
