# @generated by @newel/generator-godot — do not edit
class_name VeilStalkerData
extends Resource

enum Tier {
	TIER_1,
	TIER_2,
	TIER_3,
	TIER_4,
	TIER_5,
}

enum Aggressionlevel {
	PASSIVE,
	NEUTRAL,
	AGGRESSIVE,
	TERRITORIAL,
}

enum State {
	IDLE,
	ALERT,
	AGGRESSIVE,
	FLEEING,
	DEAD,
	RESPAWNING,
}
