# @generated by @newel/generator-godot — do not edit
class_name KnowledgeByExperimentationData
extends Resource

enum Status {
	PROPOSED,
	ACCEPTED,
	SUPERSEDED,
}

@export var id: String
@export var status: int
