# @generated by @newel/generator-godot — do not edit
class_name PersistenceSystemData
extends Resource


@export var id: String
@export var serverSaveDir: String
@export var worldFileName: String
@export var playerFilePrefix: String
@export var autosaveIntervalSeconds: int
@export var shutdownRequestPath: String
@export var atomicWrites: bool
