# @generated by @newel/generator-godot — do not edit
class_name WorldSystemData
extends Resource


@export var id: String
@export var circumferenceKm: float
@export var polarLatitude: float
@export var seaLevel: float
