# @generated by @newel/generator-godot — do not edit
class_name WorldSystemData
extends Resource


@export var id: String
@export var circumferenceKm: float
@export var polarLatitude: float
@export var seaLevel: float
@export var minHeight: float
@export var maxHeight: float
@export var oceanShare: float
@export var heightSpline: Array
@export var ridgeAmplitude: float
@export var spawnHabitableBiomes: Array
@export var spawnMinColonizedDistance: float
@export var colonizedScore: float
@export var friendSpawnRadius: float
