# @generated by @newel/generator-godot — do not edit
class_name RecipeStaminaPotionData
extends Resource

enum Domain {
	SMITHING,
	ALCHEMY,
	ARCANE,
	CARPENTRY,
}


@export var id: String
@export var domain: int
@export var outputCount: int
