# @generated by @newel/generator-godot — do not edit
class_name InventoryData
extends Resource

enum State {
	OPEN,
	CLOSED,
	FULL,
}

@export var id: String
@export var state: int
@export var maxSlots: int
@export var maxWeightKg: float
@export var usedSlots: int
@export var currentWeightKg: float
