# @generated by @newel/generator-godot — do not edit
class_name PlayerCharacterData
extends Resource

enum State {
	ALIVE,
	DEAD,
	RESPAWNING,
}

@export var id: String
@export var state: int
@export var name: String
@export var baseHp: int
@export var currentHp: int
@export var baseSpeed: float
@export var positionX: float
@export var positionY: float
@export var positionZ: float
