# @generated by @newel/generator-godot — do not edit
extends Node
# Add to Project → Autoload as "GameData"

const APPEARANCES: Dictionary = {
		"BoarRider": preload("res://godot/appearances/boarrider.tres"),
		"TravellerHuman": preload("res://godot/appearances/travellerhuman.tres")
}

const BIOMES: Dictionary = {
		"TemperateForest": preload("res://godot/biomes/temperateforest.tres"),
		"TemperateGrassland": preload("res://godot/biomes/temperategrassland.tres"),
		"TwilightGrove": preload("res://godot/biomes/twilightgrove.tres"),
		"VoidRift": preload("res://godot/biomes/voidrift.tres"),
		"VolcanicBadlands": preload("res://godot/biomes/volcanicbadlands.tres")
}

const CREATURES: Dictionary = {
		"CinderGargoyle": preload("res://godot/creatures/cindergargoyle.tres"),
		"ForestBoar": preload("res://godot/creatures/forestboar.tres"),
		"GlimmerFox": preload("res://godot/creatures/glimmerfox.tres"),
		"GraywolfPack": preload("res://godot/creatures/graywolfpack.tres"),
		"LavaSlug": preload("res://godot/creatures/lavaslug.tres"),
		"RidgeHawk": preload("res://godot/creatures/ridgehawk.tres"),
		"RiftWarden": preload("res://godot/creatures/riftwarden.tres"),
		"SteppeBison": preload("res://godot/creatures/steppebison.tres"),
		"VeilStalker": preload("res://godot/creatures/veilstalker.tres"),
		"VoidSerpent": preload("res://godot/creatures/voidserpent.tres")
}

const DECISIONS: Dictionary = {
		"DestructibleBuildings": preload("res://godot/decisions/destructiblebuildings.tres"),
		"FictionalMaterials": preload("res://godot/decisions/fictionalmaterials.tres"),
		"GodotEngine": preload("res://godot/decisions/godotengine.tres"),
		"KnowledgeByExperimentation": preload("res://godot/decisions/knowledgebyexperimentation.tres"),
		"MagicBalancedWithMartial": preload("res://godot/decisions/magicbalancedwithmartial.tres"),
		"NoTeleportation": preload("res://godot/decisions/noteleportation.tres"),
		"OfflinePlayerNpcs": preload("res://godot/decisions/offlineplayernpcs.tres"),
		"OnePersistentWorld": preload("res://godot/decisions/onepersistentworld.tres")
}

const ITEMS: Dictionary = {
		"AethermiteBow": preload("res://godot/items/aethermitebow.tres"),
		"AethermiteDust": preload("res://godot/items/aethermitedust.tres"),
		"AethermiteShard": preload("res://godot/items/aethermiteshard.tres"),
		"AlchemyPotion": preload("res://godot/items/alchemypotion.tres"),
		"AshiteBlock": preload("res://godot/items/ashiteblock.tres"),
		"CarpenterAxe": preload("res://godot/items/carpenteraxe.tres"),
		"DuskfiberCloak": preload("res://godot/items/duskfibercloak.tres"),
		"EnchantedAethermiteShard": preload("res://godot/items/enchantedaethermiteshard.tres"),
		"FerriteHelmet": preload("res://godot/items/ferritehelmet.tres"),
		"FerriteIngot": preload("res://godot/items/ferriteingot.tres"),
		"FerritePick": preload("res://godot/items/ferritepick.tres"),
		"FerriteShield": preload("res://godot/items/ferriteshield.tres"),
		"FerriteShortSword": preload("res://godot/items/ferriteshortsword.tres"),
		"FieldRations": preload("res://godot/items/fieldrations.tres"),
		"LumenfiteOrb": preload("res://godot/items/lumenfiteorb.tres"),
		"ThornwoodPlank": preload("res://godot/items/thornwoodplank.tres"),
		"VeilsteelChestplate": preload("res://godot/items/veilsteelchestplate.tres"),
		"VeilsteelIngot": preload("res://godot/items/veilsteelingot.tres"),
		"VeilsteelLongsword": preload("res://godot/items/veilsteellongsword.tres"),
		"VeilsteelPick": preload("res://godot/items/veilsteelpick.tres"),
		"VoidRuneTablet": preload("res://godot/items/voidrunetablet.tres"),
		"VoiditeEdge": preload("res://godot/items/voiditeedge.tres")
}

const LOOTS: Dictionary = {
		"LootTable": preload("res://godot/loots/loottable.tres")
}

const MATERIALS: Dictionary = {
		"Aethermite": preload("res://godot/materials/aethermite.tres"),
		"Ashite": preload("res://godot/materials/ashite.tres"),
		"Duskfiber": preload("res://godot/materials/duskfiber.tres"),
		"Ferrite": preload("res://godot/materials/ferrite.tres"),
		"Lumenfite": preload("res://godot/materials/lumenfite.tres"),
		"Thornwood": preload("res://godot/materials/thornwood.tres"),
		"Veilsteel": preload("res://godot/materials/veilsteel.tres"),
		"Voidite": preload("res://godot/materials/voidite.tres")
}

const PALETTES: Dictionary = {
		"DefaultPalette": preload("res://godot/palettes/defaultpalette.tres")
}

const PLAYERS: Dictionary = {
		"Inventory": preload("res://godot/players/inventory.tres"),
		"PlayerCharacter": preload("res://godot/players/playercharacter.tres")
}

const PROFESSIONS: Dictionary = {
		"Alchemist": preload("res://godot/professions/alchemist.tres"),
		"Arcanist": preload("res://godot/professions/arcanist.tres"),
		"Blacksmith": preload("res://godot/professions/blacksmith.tres"),
		"Merchant": preload("res://godot/professions/merchant.tres"),
		"Pathfinder": preload("res://godot/professions/pathfinder.tres"),
		"Ranger": preload("res://godot/professions/ranger.tres"),
		"VoidTouched": preload("res://godot/professions/voidtouched.tres"),
		"Warrior": preload("res://godot/professions/warrior.tres")
}

const RECIPES: Dictionary = {
		"RecipeAethermiteBow": preload("res://godot/recipes/recipeaethermitebow.tres"),
		"RecipeAshiteBlock": preload("res://godot/recipes/recipeashiteblock.tres"),
		"RecipeCarpenterAxe": preload("res://godot/recipes/recipecarpenteraxe.tres"),
		"RecipeDuskfiberCloak": preload("res://godot/recipes/recipeduskfibercloak.tres"),
		"RecipeEnchantedAethermiteShard": preload("res://godot/recipes/recipeenchantedaethermiteshard.tres"),
		"RecipeFerriteIngot": preload("res://godot/recipes/recipeferriteingot.tres"),
		"RecipeFerritePick": preload("res://godot/recipes/recipeferritepick.tres"),
		"RecipeFerriteShortSword": preload("res://godot/recipes/recipeferriteshortsword.tres"),
		"RecipeHealthPotion": preload("res://godot/recipes/recipehealthpotion.tres"),
		"RecipeLumenfiteOrb": preload("res://godot/recipes/recipelumenfiteorb.tres"),
		"RecipeStaminaPotion": preload("res://godot/recipes/recipestaminapotion.tres"),
		"RecipeThornwoodPlank": preload("res://godot/recipes/recipethornwoodplank.tres"),
		"RecipeVeilsteelChestplate": preload("res://godot/recipes/recipeveilsteelchestplate.tres"),
		"RecipeVeilsteelIngot": preload("res://godot/recipes/recipeveilsteelingot.tres"),
		"RecipeVeilsteelLongsword": preload("res://godot/recipes/recipeveilsteellongsword.tres"),
		"RecipeVoidResistPotion": preload("res://godot/recipes/recipevoidresistpotion.tres"),
		"RecipeVoidRuneTablet": preload("res://godot/recipes/recipevoidrunetablet.tres")
}

const SKELETONS: Dictionary = {
		"BirdSkeleton": preload("res://godot/skeletons/birdskeleton.tres"),
		"HumanoidSkeleton": preload("res://godot/skeletons/humanoidskeleton.tres"),
		"QuadrupedSkeleton": preload("res://godot/skeletons/quadrupedskeleton.tres"),
		"SerpentSkeleton": preload("res://godot/skeletons/serpentskeleton.tres")
}

const SKILLS: Dictionary = {
		"Alchemy": preload("res://godot/skills/alchemy.tres"),
		"ArcaneForging": preload("res://godot/skills/arcaneforging.tres"),
		"Archery": preload("res://godot/skills/archery.tres"),
		"Carpentry": preload("res://godot/skills/carpentry.tres"),
		"Cartography": preload("res://godot/skills/cartography.tres"),
		"Diplomacy": preload("res://godot/skills/diplomacy.tres"),
		"ElementalMagic": preload("res://godot/skills/elementalmagic.tres"),
		"Enchanting": preload("res://godot/skills/enchanting.tres"),
		"Leadership": preload("res://godot/skills/leadership.tres"),
		"Navigation": preload("res://godot/skills/navigation.tres"),
		"RestorationMagic": preload("res://godot/skills/restorationmagic.tres"),
		"Shieldcraft": preload("res://godot/skills/shieldcraft.tres"),
		"Smithing": preload("res://godot/skills/smithing.tres"),
		"Speechcraft": preload("res://godot/skills/speechcraft.tres"),
		"Stealth": preload("res://godot/skills/stealth.tres"),
		"Swordsmanship": preload("res://godot/skills/swordsmanship.tres"),
		"Tracking": preload("res://godot/skills/tracking.tres"),
		"Trade": preload("res://godot/skills/trade.tres"),
		"Unarmed": preload("res://godot/skills/unarmed.tres"),
		"VoidMagic": preload("res://godot/skills/voidmagic.tres"),
		"VoidSmithing": preload("res://godot/skills/voidsmithing.tres")
}

const SYSTEMS: Dictionary = {
		"BelievableNotRealistic": preload("res://godot/systems/believablenotrealistic.tres"),
		"CivilizationIsPlayerMade": preload("res://godot/systems/civilizationisplayermade.tres"),
		"CommunityOwnsTheFuture": preload("res://godot/systems/communityownsthefuture.tres"),
		"DeathSignal": preload("res://godot/systems/deathsignal.tres"),
		"EverythingHasTradeoffs": preload("res://godot/systems/everythinghastradeoffs.tres"),
		"FreedomComesFirst": preload("res://godot/systems/freedomcomesfirst.tres"),
		"KnowledgeIsProgression": preload("res://godot/systems/knowledgeisprogression.tres"),
		"MonetizationRules": preload("res://godot/systems/monetizationrules.tres"),
		"NoPayToWin": preload("res://godot/systems/nopaytowin.tres"),
		"PlayersAreTheContent": preload("res://godot/systems/playersarethecontent.tres"),
		"SystemsOverScripts": preload("res://godot/systems/systemsoverscripts.tres"),
		"TheWorldIsPersistent": preload("res://godot/systems/theworldispersistent.tres")
}

const TECHNOLOGIES: Dictionary = {
		"TechAlchemy": preload("res://godot/technologies/techalchemy.tres"),
		"TechArcaneForging": preload("res://godot/technologies/techarcaneforging.tres"),
		"TechBasicCarpentry": preload("res://godot/technologies/techbasiccarpentry.tres"),
		"TechBasicSmithing": preload("res://godot/technologies/techbasicsmithing.tres"),
		"TechMasterForge": preload("res://godot/technologies/techmasterforge.tres"),
		"TechTextileWeaving": preload("res://godot/technologies/techtextileweaving.tres"),
		"TechVoidMastery": preload("res://godot/technologies/techvoidmastery.tres")
}

const WORLD_SYSTEMS: Dictionary = {
		"CombatSystem": preload("res://godot/world_systems/combatsystem.tres"),
		"GovernanceSystem": preload("res://godot/world_systems/governancesystem.tres"),
		"MarketSystem": preload("res://godot/world_systems/marketsystem.tres"),
		"TradeSystem": preload("res://godot/world_systems/tradesystem.tres"),
		"WeatherSystem": preload("res://godot/world_systems/weathersystem.tres")
}

