# @generated by @newel/generator-godot — do not edit
class_name VoidRiftData
extends Resource


@export var id: String
@export var avgTemperature: float
@export var avgRainfall: float
@export var soilFertility: float
