# @generated by @newel/generator-godot — do not edit
class_name VolcanicBadlandsData
extends Resource


@export var id: String
@export var avgTemperature: float
@export var avgRainfall: float
@export var soilFertility: float
@export var treeDensity: int
@export var surfaceMaterial: String
@export var surfaceTint: String
@export var soilTint: String
@export var topsoilDepth: float
@export var soilMaterial: String
@export var temperature: Dictionary
@export var moisture: Dictionary
@export var altitude: Dictionary
@export var rarity: float
@export var surfaceVeinChance: float
