# @generated by @newel/generator-godot — do not edit
class_name DiplomacyData
extends Resource

enum XpCurve {
	LINEAR,
	QUADRATIC,
	EXPONENTIAL,
}

enum Category {
	COMBAT,
	CRAFTING,
	MAGIC,
	EXPLORATION,
	SOCIAL,
}

enum Tier {
	NOVICE,
	APPRENTICE,
	JOURNEYMAN,
	EXPERT,
	MASTER,
}
