# @generated by @newel/generator-godot — do not edit
# IR version: 3.0.0
extends Resource
class_name RestorationMagicData

enum XpCurve {
	LINEAR,
	QUADRATIC,
	EXPONENTIAL,
}

enum Category {
	COMBAT,
	CRAFTING,
	MAGIC,
	EXPLORATION,
	SOCIAL,
}

enum State {
	NOVICE,
	APPRENTICE,
	JOURNEYMAN,
	EXPERT,
	MASTER,
}
