# @generated by @newel/generator-godot — do not edit
extends Resource
class_name SpeechcraftData

enum Xpcurve {
	LINEAR,
	QUADRATIC,
	EXPONENTIAL,
}

enum Category {
	COMBAT,
	CRAFTING,
	MAGIC,
	EXPLORATION,
	SOCIAL,
}

enum State {
	NOVICE,
	APPRENTICE,
	JOURNEYMAN,
	EXPERT,
	MASTER,
}
